### ISSUE TITLE
consistent API for computing stable points

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1002]
HARK allows for the computation of stable points (such as steady state normalized market resources) the most basic object-oriented solver, and I suppose this is inherited by other OO solvers.

https://github.com/econ-ark/HARK/blob/6d157ea5164dd8de5e730b0c364588826a728fb4/HARK/ConsumptionSaving/ConsIndShockModel.py#L503

This is useful functionality that is lost in classes for which a separate functional solver is defined, such as ConsPortfolioModel:

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsPortfolioModel.py#L508

While theoretically allowing for unconstrained customizability of solver functionality may sound like a good thing, it would be better if we had a consistent API for doing useful things across models.

**Comment by mnwhite** [comment]
This method has been moved out of the solver, because it was a major source of slowdown. Closing because there's a duplicative issue that calls for a universal "find stable points" method.
