### ISSUE TITLE
PerfectForesight solution missing mNrmStE quietly

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1005]
I'm running into an issue where PerfectForesight model solutions _most_ of the time have a `mNrmStE` property, but under some conditions they quietly don't. This "silent failure" is an issue as this is part of a simulation that uses an automatically generated population of agents.

This is over a population of agent models that are mostly like HARK defaults, though they vary with respect to the `CRRA` and `DiscFac` parameters.

I suspect this is because the particular parameter combination is running up against some of the "conditions" of the model, such as GIC. However, as far as I know the PerfectForesight model does not have `check_conditions` capability.

These are the parameters of one of the models that fails to have an `mNrmStE`.

```
<HARK.ConsumptionSaving.ConsIndShockModel.PerfForesightConsumerType object at 0x7efe82ad0ee0.
Parameters:
CRRA: 2
Rfree: 1.043014272544372
DiscFac: 0.9738
LivPrb: [0.9949620563926881]
PermGroFac: [1.0024906793143211]
BoroCnstArt: 0.0
MaxKinks: 400
AgentCount: 2
aNrmInitMean: 2
aNrmInitStd: 0.0
pLvlInitMean: 1.0
pLvlInitStd: 0.0
PermGroFacAgg: 1.0
T_age: None
T_cycle: 1
aXtraMin: 0.001
aXtraMax: 100
aXtraNestFac: 1
aXtraCount: 200
aXtraExtra: [None]
PermShkStd: [0.6191893521335157]
PermShkCount: 7
TranShkStd: [0.1658834945210779]
TranShkCount: 7
UnempPrb: 0.05
UnempPrbRet: 0.005
IncUnemp: 0.3
IncUnempRet: 0.0
tax_rate: 0.0
T_retire: 0
vFuncBool: False
CubicBool: False
RiskyAvg: 1.043014272544372
RiskyStd: 0.056143696919254374
RiskyCount: 5
ShareCount: 25
AdjustPrb: 1.0
DiscreteShareBool: False>
```

**Comment by mnwhite** [comment]
This has been resolved. In situations where the mNrmStE or mNrmTrg don't exist (because of condition failures or failure to find), they are set as NaN.
