### ISSUE TITLE
Reducing pytest approx_equals sensitivity to only 6 decimal places

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1009]
From @llorracc in #1006 

> Some of the failures were approx_equal failures in which the new solutions were correct to six but not seven decimal places. I couldn't figure out where to dial back the default degree of precision to six, which is enough for our purposes anyway.

**Comment by sbenthall** [comment]
Any ideas @MridulS ?

**Comment by llorracc** [comment]
@MridulS , 

Renewing this because -- as @alanlujan91 seems to have figured out -- a new version of numpy seems to change some very fine details of matrix multiplication that affect things way down in like the 14th digit.  Could you look into whether there is a global way to turn down the sensitivity of the assertEqual thing?  In the meantime I'll ask @alanlujan91 to see if reducing the length of a few of the asserted numbers fixes the problem.

**Comment by Mv77** [comment]
Seems not to be matrix multiplication but geometric distributions or something like that.

**Comment by alanlujan91** [comment]
I believe it's due to this change although I could be wrong

 https://numpy.org/devdocs/release/1.21.0-notes.html#generator-rayleigh-and-generator-geometric-performance-improved

**Comment by mnwhite** [comment]
Well that will cause *everything* to fail tests just about. What we should
have done is had a trivial RNG test that *only* makes draws from numpy
distributions. If those ever fail, it means the RNG system has changed and
we need to re-compute our test targets (in their own PR).

**Comment by sbenthall** [comment]
We should pin the numpy dependency to the prior version so tests pass and development is not blocked.

Then we can update numpy and correct the tests in one clean PR.

**Comment by sbenthall** [comment]
Please see #1029

Because pinning numpy to v1.19.4 did not clear the tests by itself, that disconfirms the hypothesis that the failure was due to a recent numpy RNG update.

My guess is that the underlying cause is GitHub infrastructure changes.

Changing a few of the tests from `assertEquals` to `assertAlmostEquals`, which bounds the number of significant digits of agreement, solved the immediate issue of test failures.

This does not address the broader problem of this issue, to which #1025 is scoped.

**Comment by sbenthall** [comment]
`assertAlmostEquals` takes an optional `places` argument that can change the number of significant digits the test is sensitive to.

https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual

This could be changed for individual tests. Or, to make a wider change, a new method could be made that wraps this method with [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) by doing something like:

```
from functools import partial

assertAlmostEqual5 = partial(assertAlmostEqual, places = 5)
```

**Comment by llorracc** [comment]
To pursue and extend @sbenthall's point:  What we would really like is the ability to set the number of digits to match.  Probably we should be content to match everything to 4 or 5 digits, but it would be good to be able to set the number of digits globally, as well as specifically for each test.  For example, models simulated using the transition matrix method will inevitably yield modestly different results than those simulted using Monte Carlo, except in the limit as the size of both the transition matrix and the Monte Carlo populations approach infinity.  @wdu9 has been working on comparing results from those two methods, and while there seems to be a bug right now causing them to be much more different than they should be, I anticipate that he'll soon be able to fix that bug and we will want to test the results from the transition matrix simulations to the "benchmark" Monte Carlo results at a much smaller number of digits of significance (like, maybe 3).
