### ISSUE TITLE
KinkedRsolver: Add cubic interpolation

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#103]
The solver for ConsKinkedR currently requires CubicBool to be False and terminates immediately otherwise.  When this restriction is removed, the solver runs successfully (at the parameters in ConsumerParameters.py), and the solution is *almost but not quite* correct: both ends of the kink are smooth rather than, you know, kinked.  This is because CubicInterp uses the MPC as the slope at the endpoints, but it should be 1.0 for just the kink segment.  (Change the bounds of the cFunc plot to [0.8,1.0] to see what I mean.)

The fix is to overwrite makeCubiccFunc in ConsKinkedRsolver.  It should first run ConsIndShockSolver.makeCubiccFunc, then manually change the cubic spline coefficients in cFuncNowUnc on the kinked segment to match the endpoint levels and have slope of 1, returning the edited interpolation.  I expect this will be 4-8 lines.

**Comment by mnwhite** [comment]
For someone new to HARK who wants to take a crack at this:

- The class HARK.interpolation.CubicInterp represents piecewise cubic spline interpolators.

- To approximate a function y = f(x) using data at domain values {x}, the init method for this class takes 1D arrays of {x}, {y}, and {dy/dx}-- the level and slope of the function at some gridpoints.  It also has some optional inputs, but they aren't important.

- The cubic polynomial coefficients for an instance of CubicInterp are stored in the attribute coeffs.  The init method assumes that you want a smooth function-- to match the level and slope of the function as specified-- but that's not quite the case here.

- In this case, the function of interest has exactly two kinks.  It is smooth below the first kink and above the second kink, and has a slope of exactly 1 in between.  The CubicInterp representation of this function is incorrect on the linear portion of the function.

- The kinks corresponds to the two gridpoints that were generated from aNrm=0.  First thing: Identify the index where the kinks are. That is, which segment of the piecewise cubic interpolation *should* be linear.

- Second thing: Change the coefficients on that segment to be linear; the quadratic and cubic coefficients are zero, and the constant coefficient is simply y[i]-x[i].  However, note that the linear coefficient isn't *actually* 1.0.  Each segment of the interpolation is remapped to the unit interval [0,1], so a segment that spans [a,b] with a slope of 1 for the "true" function should have a slope of (b-a) = (x[i+1] - x[i]) in the remapped coefficients.

**Comment by mnwhite** [comment]
Note: Also need to remove the "safety" that throws an error/warning when CubicBool is True (at the very beginning of the solver).

**Comment by MridulS** [comment]
fixed in https://github.com/econ-ark/HARK/pull/386
