### ISSUE TITLE
no default cycles value

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1030]
From #1022 , @mnwhite says:

> Yeah, cycles=1 should be removed as a default argument. I think I wrote
> that in the very earliest versions (late summer / early fall 2015) and it's
> never come off.

**Comment by mnwhite** [comment]
In AgentType subclasses, there should be *no* default. This is something we
want to be in the parameter dictionary. I'm indifferent about what our
example dictionaries have, but this default shouldn't exist at all.

**Comment by sbenthall** [comment]
Oh, I see. I'll correct that in the title of this issue.
This is what I'll work on next as it will make #1022 easier.
