### ISSUE TITLE
initialize_sim doesn't seem to init state variables

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#1032]
Around line 502 of core.py, in AgentType.initialize_sim, it looks like the code is supposed to loop through and blank out all state variables with these lines:

`for var in self.state_now:`
....`            if self.state_now[var] is None:`
........`                self.state_now[var] = copy(blank_array)`

This doesn't seem to do what it's supposed to. I think it should loop over `var in self.state_vars`, which names all of the state variables. Moreover, I'm not sure what that if statement is supposed to do. If this is the very first time that initialize_sim() is called, then nothing will be in self.state_now at all and this will crash. More generally, when we're initializing, don't we *definitely* want to put blank arrays in these spots?

I just updated one of my projects to the latest version of HARK (in the repo, running in developer mode), and I can get it to work properly if I change those three lines to just:

`for var in self.state_vars:`
....`            self.state_now[var] = copy(blank_array)`

**Comment by sbenthall** [comment]
It doesn't really make sense to store _both_ a list of all state variables _and_ have a dictionary with an entry for every state variable. All the information in the former is in the latter.

`for var in self.state_now` loops over all the _keys_ in `state_now`, which are the state variable names.

Maybe you could solve the problem in a different way by populating the state_now dictionary?

I agree that the code is probably in a halfway state between two designs and that this is confusing. I would prefer further deprecation of the lists of state vars.

**Comment by sbenthall** [comment]
One source of awkwardness -- not sure if it's related to this -- is that sometimes state_vars are aggregate variables with scalar values instead of arrays.

Maybe the current code is set up so that it's possible to populate a state variable with a scalar in `initalize_sim` in some subclasses code?

I do not love the current handling of aggregate state variables and if this was what was causing confusion would not mind a rethink of the design of that.

I wonder if you proposed change to the core code breaks any tests.

**Comment by mnwhite** [comment]
Sure, but how does that dictionary get created? How does it know what
variables should be in the dictionary? I thought that's what state_vars is
for?

Wait, I found the issue: state_vars does exist, but it has to be defined at
the class level, not within the init method for the class for each
instance. That's fine, this works. And state_vars is not something that
should vary across instances.
