### ISSUE TITLE
PerfForesight: add constrained capability

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#104]
As is, ConsPerfForesightSolver can't handle (and doesn't task as an input) an artificial borrowing constraint.  Fixing this will require a complete rewrite of the solver, which currently only produces a linear cFunc with a single segment.  Constrained solution will be piecewise linear, and I think we use information about next period's kink locations to find this period's.

Could be done in conjunction with fixing issue #75.

**Comment by mnwhite** [comment]
Related, Sheng Guo at FIU tried to use PerfForesight to solve a cake-eating problem (endowment only, no income), but there is currently no way to do this.  A while back we briefly discussed adding a boolean input for PerfForesightSolver that specifies whether income will be received next period.  This would allow solution to perfect foresight models where income is only received in some periods, as well as cake-eating problems with no income at all.

**Comment by mnwhite** [comment]
Clarification: You can't do a cake-eating problem with the perfect foresight model.  I believe you can do it with ConsIndShock.

**Comment by compumetrika** [comment]
AH that makes sense. Was going to suggest playing around with ConsIndShock
but question already answered.

**Comment by mnwhite** [comment]
One of my graduate students is tackling this for her project for my numeric methods class.

**Comment by mnwhite** [comment]
The student has (more or less) completed the work for this.  I will try to move it over and give her credit.

**Comment by mnwhite** [comment]
This has been completed and ready to merge for a couple months; see #299

**Comment by MridulS** [comment]
https://github.com/econ-ark/HARK/pull/299 is merged, closing this.
