### ISSUE TITLE
cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by iworld1991** [econ-ark/HARK#1043]
**Describe the bug**

time.clock is deprecated in Python 3.8, but HARK.utilities still imports clock from time, causing an error pasted as below.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-aeec6eb5c597> in <module>
      3 from copy import deepcopy, copy
      4 import numpy as np
----> 5 from HARK.ConsumptionSaving.ConsIndShockModel import init_idiosyncratic_shocks
      6 from HARK.ConsumptionSaving.ConsMarkovModel import MarkovConsumerType
      7 from HARK.distribution import DiscreteDistribution

~/opt/anaconda3/envs/econ-ark/lib/python3.9/site-packages/HARK/__init__.py in <module>
      1 from __future__ import absolute_import
----> 2 from .core import *
      3 
      4 __version__ = '0.10.2'
      5 

~/opt/anaconda3/envs/econ-ark/lib/python3.9/site-packages/HARK/core.py in <module>
     19 from copy import copy, deepcopy
     20 import numpy as np
---> 21 from time import clock
     22 from .parallel import multiThreadCommands, multiThreadCommandsFake
     23 

ImportError: cannot import name 'clock' from 'time' (unknown location)

**Comment by MridulS** [comment]
This has been solved in the new releases, you can upgrade the package using `pip install -U econ-ark`.
