### ISSUE TITLE
Documentation: dill now included in Anaconda

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#106]
Our documentation gives instructions to get the packages joblib and dill using conda, but the newest version(s) of Anaconda come with dill automatically included.  Documentation should be updated to include this.  Hopefully in the future they make joblib part of the default installation and we can drop that stuff entirely (and move the stuff in HARKparallel elsewhere).

**Comment by brainwane** [comment]
@apthorpe is this something you could help us with?

**Comment by mnwhite** [comment]
The installation instructions in HARKmanual are now entirely outdated, given the packify-ing, and need to be wholly replaced.  I'm not sure we updated the README.md.

This weekend I will try to make a bunch of documentation issues to break down the manual rewrite and notebooks that we need to create.

**Comment by mnwhite** [comment]
Closing per above post, making new issue momentarily.
