### ISSUE TITLE
Improve backward compatibility when adding features

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#1065]
The PerfMITShock feature has been added to the perfect foresight model, but this has knock-on effects on all other consumption saving models. This attribute is now required to exist in all class dictionaries, which doesn't feel intuitive. That is, the user always needs to specify that they're *not* running a particular experiment. For new features like this that are meant to be optional, we should build in a default value: if you don't mention MIT shocks, you're not using them.

**Comment by sbenthall** [comment]
Should the implementation be changed so that the backwards compatibility is restored?

**Comment by sbenthall** [comment]
I would call this a bug to be fixed before the next release.

**Comment by sbenthall** [comment]
@wdu9

**Comment by sbenthall** [comment]
Reviewing tickets, I just found this issue from @mnwhite , which concerns additions made in connection to this other issue #1106 

I forget if this backwards compatibility issue was addressed before cutting the 0.12.0 release.

**Comment by llorracc** [comment]
I believe that @wdu9 fixed this by making the parameter optional.  @wdu, can you confirm?

**Comment by wdu9** [comment]
@llorracc @sbenthall  I did submit a pull request (#1067) however it was never reviewed nor merged.

**Comment by llorracc** [comment]
It is ready to be reviewed and to merge as far as you are concerned?  (It passes tests, etc?)

**Comment by wdu9** [comment]
It is ready to be reviewed. It has passed all the checks and I just ran the pytest locally on my laptop again just to be sure.

**Comment by mnwhite** [comment]
This was resolved 2.5 years ago, closing.
