### ISSUE TITLE
distribute_params and random seeds -- a truly random random seed?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1075]
The `distribute_params` method is designed to let you clone an AgentType while distributing the new Agents over a distribution over a single parameter, such as `DiscFac`.

https://github.com/econ-ark/HARK/blob/910bff34d6e1d59e686029076ca82a6cf81553c2/HARK/core.py#L1664

Using this feature, I've been surprised when the resulting AgentTypes all have perfectly correlated income shocks.

In hindsight, I should not have been surprised: these AgentTypes all have the same random seed.

However, correcting for this issue required some hacky custom code, looping over the agents, changing their seeds, reseting their RNGs, etc.

While having default and steady random seeds is very useful for testing and development, in Monte Carlo simulations with mutliple runs of the same model, you want actually random random seeds.

HARK could better support this with some kind of flag in the AgentType constructor that, if True, gave the agent a _random_ seed (using the larger computing system to provide the entropy).

A corresponding argument could be added to `distribute_params``

**Comment by mnwhite** [comment]
I think this issue was resolved (and the missing connection to central RNG as well). To the extent there's something left to do, it's on the documentation side, directing users on how to set seeds for AgentType instances.
