### ISSUE TITLE
further simplifying construct_lognormal_income_process  ?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1111]
There's been a lot of great work on `construct_lognormal_income_process` lately.

I think there may be ways to make it even smoother and more modular.

A few points:
 - It is written as a method of the `IndShockConsumerType` class with a single argument, `self`, but it uses many parameter values of that model. These parameter values are being accessed in the "whiteboard" way (see  #889), rather than via the parameters dictionary. This makes it hard to use this function outside of a very particular context. The arguments could be keyword arguments, it could access the parameters using `self.parameters` -- there are many ways to smooth over this irregularity.
 -  It's odd that `PermShkCount` is a scalar when given to the model, but that it's expanded into a `PermShkCount_list` before constructing the income distributions. Why isn't the PermShkCount a list to begin with? Why is retirement such a special case, with the count == 1?

The mechanics here seem to be about navigating: (a) unemployment as a modification to the lognormal income process, and (b) a somewhat sparsely parameterized retirement phase.

Could this be considered a special case of and `age-varying` model? (See #997)

If so, maybe there is a way to structure this method differently so that it is closer to a HARK 2.0 design. I.e., rather than having one function piece together parameter lists based on some hard-coded model assumptions and produce a set of distributions, begin with two differently parameterized models (middle age, and retirement) and then have a function that combines the models together.

**Comment by Mv77** [comment]
> * It's odd that `PermShkCount` is a scalar when given to the model, but that it's expanded into a `PermShkCount_list` before constructing the income distributions. Why isn't the PermShkCount a list to begin with? Why is retirement such a special case, with the count == 1?

That's my own doing. I thought it needed to be a list in order to pass it to `IndexDstn`, since the engine needs it. One could, alternatively, define a lambda function that just called the engine with that fixed parameter. But then new engine would not be a distribution, it would be a function.

**Comment by Mv77** [comment]
Keep me in the loop about these updates in any case.

It is in my best interest to update and flexibilize the income process. The first step was the `IndexDstn` incorporation from a few days ago, but there are more steps I'd like to take... soon<sup>TM</sup>

**Comment by llorracc** [comment]
> The mechanics here seem to be about navigating: (a) unemployment as a modification to the lognormal income process, and (b) a somewhat sparsely parameterized retirement phase.
> ...
> If so, maybe there is a way to structure this method differently so that it is closer to a HARK 2.0 design. I.e., rather than having one function piece together parameter lists based on some hard-coded model assumptions and produce a set of distributions, begin with two differently parameterized models (middle age, and retirement) and then have a function that combines the models together.

Relating these points to each other: 

In my view the construction of the transitory shock distribution should be broken into steps:  The generation of something like TranShkEmp which would be a standard discretized mean-one lognormal essentially idential to the PermShk, and then a step that adds the unemployment state to the TranShkEmp distribution.  This would be helpful in particular in my long-term dream of implementing the reshuffling approach to Monte Carlo simulation: The TranShkEmp distribution would be equiprobable and the combined distribution should be structured so that it is easy to retrieve the unemployment probability.  This would also make it easier to extend the model so that the unemployment process is a Markov state: We could keep exactly the same TranShkEmp distribution, but incorporate the Markov unemployment process independently.

**Comment by Mv77** [comment]
> In my view the construction of the transitory shock distribution should be broken into steps: The generation of something like TranShkEmp which would be a standard discretized mean-one lognormal essentially idential to the PermShk, and then a step that adds the unemployment state to the TranShkEmp distribution.

Chris, I think that's how it's done already. See

https://github.com/econ-ark/HARK/blob/ef8d8fd62bb8a06763eeeb459e2a7711b82c923c/HARK/ConsumptionSaving/ConsIndShockModel.py#L2802-L2810

**Comment by mnwhite** [comment]
What Seb proposes can be added via the constructors functionality. The "hardcoding" of raw parameters for the income process is gone, and users can now specify alternate ways of constructing IncShkDstn. Closing.
