### ISSUE TITLE
KinkedRConsumerType notebook breaking automated execution

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1134]
I'm getting an error report on a failing automated execution of the KinkedRConsumerType notebook:

https://github.com/econ-ark/HARK/runs/6016730828

Most likely due to this recent change:
https://github.com/econ-ark/HARK/commit/2a204e652b1da7f21f0ae3bbfdc62f50f0c99ec6

**Comment by mnwhite** [comment]
Closing because this must have been resolved at some point.
