### ISSUE TITLE
Borrowing Constraints in The KinkedR Model

### ISSUE THREAD

**Issue by xy244** [econ-ark/HARK#1143]

**Comment by llorracc** [comment]
Did you figure it out?  If so, it would be nice to leave a comment so that either:

1) We could improve the documentation; or 
2) Other people could benefit by reading your solution to the problem.

**Comment by mnwhite** [comment]
My recollection is that this parameter is ignored in the KinkedR model--
the whole point is that you *can* borrow, so BoroCnst=0 wouldn't be very
useful. It wouldn't be hard to turn it on if that's the case.
