### ISSUE TITLE
DemARKs are broken after recent changes

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#1169]
DemARK notebooks broke after https://github.com/econ-ark/HARK/pull/1164 was merged in. The notebooks also need to be updated with the renames.

Example build failure: https://github.com/econ-ark/DemARK/runs/8061515381

**Comment by alanlujan91** [comment]
https://github.com/econ-ark/DemARK/pull/187 should fix this

@llorracc can't remember if there's a reason we held off on this

**Comment by alanlujan91** [comment]
Closed by https://github.com/econ-ark/DemARK/pull/187
