### ISSUE TITLE
Failing tests local for econforgeinterp

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1175]
Locally, the econforgeinterp tests are failing for me:

https://gist.github.com/sbenthall/5775dff1314e56dcb08695ebfc4a4e27

I see they are passing on GitHub. So I'm wondering if there's something I need to do to update my local installation?

Any thoughts how to fix this, @Mv77 ?

**Comment by Mv77** [comment]
Yessir,

Update your econforge/interpolation.py to the latest version, or the one in
the requirements

**Comment by sbenthall** [comment]
Works! Thanks
