### ISSUE TITLE
Option to discretize uniform distribution with endpoints...

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1178]
It's useful in some cases to discretize a Uniform distribution in a way that keeps the endpoints.

We need this in SHARKFin.

**Comment by llorracc** [comment]
To codify some discussions we had about this: 

It would be useful to be able to have an atom that has infinitesimal probability.  That way, any truncated distribution we discretize will not have endpoints sensitive to things like the number of discretization points.

**Comment by alanlujan91** [comment]
closed by #1180
