### ISSUE TITLE
Numba circular import?

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#1179]
I am getting a circular import error when trying to check out the matrix simulation tools with line e.g.
`from HARK.utilities import jump_to_grid_2D`

I believe the issue has to do with the file importing numba, but there also being a `HARK.numba` file? Maybe we should change the name of `HARK.numba`? Is anyone else experiencing this issue?

**Comment by alanlujan91** [comment]
Did not happen on my end. I'll look into this more 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/5382704/195133397-2a160ae1-dbb0-41ba-98f6-23be438eb479.png">

**Comment by Mv77** [comment]
What if you
1. Set your direcctory to `HARK` (the root folder of this repo).
2. Run a script that tries to import something from numba (the package), or `HARK.utilities.jump_to_grid_2D`

**Comment by MridulS** [comment]
Yeah, we shouldn't really name the file `numba.py`, even if it works most of the times it may happen that some environment breaks it.

**Comment by alanlujan91** [comment]
Happy to change this to `HARK.fast_utils` or something like that.

**Comment by Mv77** [comment]
numbark
