### ISSUE TITLE
Improve the way we keep track of 'employment'

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#1182]
**Describe the bug**
The `get_shocks` method of `IndShkConsumerType` creates a variable that keeps track of whether an agent is employed or not. It determines whether the agent is employed by checking whether its transitory shock matches `IncUnemp`:
https://github.com/econ-ark/HARK/blob/ae96a0066563cf1f6020127232d31306be1dd425/HARK/ConsumptionSaving/ConsIndShockModel.py#L2302

This works fine if the problem is one of infinite horizon or a LC problem where `IncUnemp` is a constant. But we flexibilized the class to allow for time varying unemployment income, and this code won't work in that case (`IncUnemp` will be a list). Thus, for `self.EmpNow` to be informative in these settings, this line of code needs updating.

I might do this myself when I have a little more time but wanted to write it down so that we all remember.

**Comment by mnwhite** [comment]
See also #984 ... This bit of code needs to be taken out entirely, because "unemployment" need not exist at all now. Users will need to make a subclass of IndShockConsumerType that adds this bit of accounting code if they need it for their purposes.
