### ISSUE TITLE
Calculation of WorstIncPrb not robust to correlated income shocks

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#119]
ConsIndShockModel (and its children) use a calculation of the "worst income shock probability" (CDC denotes with the Weierstrauss p) that is not robust to negative correlation between permanent and transitory shocks.  As is, the code looks for the worst permanent shock and worst transitory shock, then finds the probability of both occurring.  If the two sets of shocks are negatively correlated, their discretization is unlikely to have such a point, so WorstIncPrb will be 0.0, and MPCmax will be 1.0.

The correct procedure for finding WorstIncPrb is fairly obnoxious: use next period's mNrmMin with the entire set of shocks to get a set of aNrmMin_candidates, choose the greatest one as the actual BoroCnstNat, then sum the probabilities of the shocks that have that aNrmMin_candidate value to get WorstIncPrb.

This hasn't come up so far because the income process has uncorrelated shocks; indeed, we still need to add a function(s) to make correlated discretized RVs.

**Comment by compumetrika** [comment]
Quantecon has some methods for discretizing a handful of processes. We can
poke around there and see if they have what we need. Off the top of my
head, here
<https://github.com/EconForge/Dolo.jl/blob/3450bdbfc019f74a78a22cc1803d65a0d09e7aeb/src/numeric/processes.jl#L186-L229>are
the processes in *Julia* -- I am running out the door, but can look around
in their Python code if we think this might be useful.

- - -- ------ ------------------------
*Nathan M. Palmer, PhD*
Computational Social Sciences
npalmer4@gmu.edu

**Comment by llorracc** [comment]
I don't really understand this: "If the two sets of shocks are negatively correlated, their discretization is unlikely to have such a point".  Unless the transitory and permanent shocks are _perfectly_ correlated, there will always be a worst outcome for the transitory and a worst outcome for the permanent shock, and a positive probability of that event occurring ...

I think maybe the point is that an unpleasant characteristic of the current approach is that the _value_ of the discretized minimum joint point will be strongly affected by the number of gridpoints chosen, which is a serious numerical flaw in the setup.

**Comment by mnwhite** [comment]
I was imagining that the (discrete) distribution of TransShk would vary
with the distribution of PermShk, as they would if we maintained an
equiprobable discrete distribution.  Suppose the two are negatively
correlated. At low values of PermShk, the lowest equiprobable TranShk value
is high; at high values of PermShk, the lowest equiprobable TranShkValue is
low.  Which *joint* (PermShk,TranShk) event is the "worst" from the
perspective of the natural borrowing constraint?  You have to check all the
points (or a plausible set of candidate points) to find out which one is
actually the most restrictive.

**Comment by llorracc** [comment]
Oh, now I get it, you're right.  

There's a parallel alternative to the equiprobable distribution, where there is a fixed set of points, and the way the correlation is introduced is by varying the probability weights for the joint outcomes.  For some reason my intuition was about that model instead of the one I've actually used a lot more,  which is the equiprobable one.

The solution to this, I think, is the same as for #121 (which is closely related): The boundaries should be set and there should be some very very tiny probability that you actually end up at the bound.

**Comment by mnwhite** [comment]
The solution for this (in a more complicated model) is in ConsAggShockModel.py around line 610.  Roughly, the procedure here is:

1) Calc aNrmMin_candidates = PermGroFac*PermShkValsNext/Rfree*(mNrmMinNext - TranShkValsNext).
2) Calc aNrmMin as the max of that (the most restrictive one).
3) Evaluate temp = aNrmMin*Rfree/(PermGroFac*PermShkValsNext) + TranShkValsNext == mNrmMinNext ... Maybe use np.isclose?
4) Calc WorstIncShkPrb = np.dot(temp, ShkPrbsNext)

Uh, I guess I just wrote most of the code for this.  So now this is really, really easy for a first timer.

**Comment by mnwhite** [comment]
This was fixed a while ago, across the various models. Closing.
