### ISSUE TITLE
New functionality: correlated discretized RVs

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#120]
As is, our only method for automatically generating discretized joint distributions is `combineIndepDstns`.  HARK.utilities should also contain methods for making discrete approximations to correlated multivariate distributions.  Three requests:

1) To start really simple: continuous uniform distribution with linear relationships.  
    * In 2D, the graph of the continuous PDF is a parallelogram; the discrete approximation would be approximately a parallelogram but with jagged edges

2) Discretized multivariate normal distribution.  Take in vector array of means and matrix array of varcov, return joint normal approximation.

3) Same as (2), but lognormal with underlying lognormal distribution as specified.

NB.  We plan to move toward a system like that of [dolo](https://github.com/EconForge/dolo) for discretizing distributions.  The best way to do this task might be to figure out how to construct a front end to dolo's [existing tools for doing this](https://dolo.readthedocs.io/en/latest/model_api.html?highlight=discretize).

This is related to #119 and #121

**Comment by econ-ark** [comment]
A full description of what is desired, with the math, is at [Chris Carroll's public lecture notes site](http://econ.jhu.edu/people/ccarroll/public/LectureNotes) in MathFacts/Equiprobable-Returns.  The problem is solved and graphs produced by Mathematica code that is part of an [archive here](http://econ.jhu.edu/people/ccarroll/public/LectureNotes/MathFacts/Equiprobable-Returns.zip]

**Comment by mnwhite** [comment]
compumetrika's (NMP) comment on #119 is probably more relevant for this issue; I think he was responding to the last line of my original post in that issue.

**Comment by sbenthall** [comment]
@Mv77

**Comment by Mv77** [comment]
I see this marked as a 1.0.0 milestone, but I have less than a week left and Chris told me to prioritize the calibration stuff.
I might get to it eventually if needed for my dissertation (likely), but that's a bit far down the line.

**Comment by sbenthall** [comment]
ok, i just moved it because I see that #623 was marked for 1.0.

I guess all this can be punted to 1.x

**Comment by llorracc** [comment]
Yes, it can be punted.  Mateo will indeed need to do it eventually but the calibration stuff nailed down is definitely higher priority.

**Comment by sbenthall** [comment]
After #640 this will depend on a representation of a correlated multivariate (e.g. lognormal) distribution.

Currently, the LogNormal distribution takes parameters `mu` and `sigma`, which may be either floats or lists of floats, and returns an `ndarray` or list of `ndarrays`. This is an artifact of earlier implementations. It is moving towards storage of `mu` and `sigma` as `ndarrays` with #811, which is slated for 1.0.

It would make sense for a multivariate lognormal distribution to take an ndarray for the covariance matrix.

You might want to consider at that point making the multivariate lognormal a generalization of the univariate lognormal class, i.e. one that takes a wider range of inputs. The multivariate independent case that is currently supported looks like yet another artifact of now regretted coding.

In my view, it would be ideal if all the inputs and outputs to the Distribution classes were `ndarrays` and not lists.

**Comment by Mv77** [comment]
It came up before I thought it would. See a first naive attempt at #948.

**Comment by llorracc** [comment]
I think Dolo has moved in this direction.  Even a univariate distribution is characterized by a (degenerate) variance/covariance matrix.   

The issue still arises of "which interpolation method should we use.  There are a lot of candidates, and I don't have the to differentiate between them.

**Comment by mnwhite** [comment]
@sidd3888 is nearly finished with the multivariate lognormal in #1412 , and multivariate normal was done long ago. I don't think my item (1) in the original post is particularly valuable or useful, and can be done "manually" when needed; it was more of a "getting started" thing. Closing.
