### ISSUE TITLE
HARKinterpolation.py

### ISSUE THREAD

**Issue by mbholm** [econ-ark/HARK#123]
On line 787 in HARKinterpolation, I got an error message when trying to run it. When I changed "xrange" to "range" it went through.

**Comment by mnwhite** [comment]
Can you copy-paste the error message for xrange?  This doesn't come up on my computers.

**Comment by mnwhite** [comment]
PS: My first / only guess is that you're using Python 3 rather than Python 2.  If the error message is something to the effect that there is no function called xrange, then it's probably Python 3.

**Comment by mbholm** [comment]
Yes, that's true. I am now in the process of installing python 2 instead.
