### ISSUE TITLE
3 Hark Documentation pages have broken Latex rendering

### ISSUE THREAD

**Issue by DominicWC** [econ-ark/HARK#1307]
Here are all the issues I could find:

https://hark.readthedocs.io/en/latest/example_notebooks/PerfForesightConsumerType.html
- In the "Example parameter values to construct an instance of PerfForesightConsumerType" table

https://hark.readthedocs.io/en/latest/example_notebooks/GenIncProcessModel.html
- Under the "General Income Process model" header

https://hark.readthedocs.io/en/latest/example_notebooks/KinkedRconsumerType.html
- Under the "Statement of “kinked R” model" header
- In the "Example parameter values to construct an instance of KinkedRconsumerType" table

**Comment by AA-Turner** [comment]
@DominicWC -- These seem to have been resolved in ``docs.econ-ark.org``:

* https://docs.econ-ark.org/example_notebooks/PerfForesightConsumerType.html#Example-parameter-values-to-construct-an-instance-of-PerfForesightConsumerType
* https://docs.econ-ark.org/example_notebooks/GenIncProcessModel.html#General-Income-Process-model
* https://docs.econ-ark.org/example_notebooks/KinkedRconsumerType.html#Statement-of-%22kinked-R%22-model

I couldn't find any further LaTeX errors on a quick search, so I'll close this issue -- but we should re-open if any more are found.

A
