### ISSUE TITLE
Demos should be in a "Demos" directory in the folder of the model being demo'd

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#134]
A number of the demos in 

/HARK/ConsumptionSaving/Demos/

(maybe all of them) actually use the cstwMPC code rather than the ConsumptionSaving codebase.  Seems like we should put the Demos for each model in a "Demos" directory _of that model_.

**Comment by mnwhite** [comment]
They use the cstwMPC *parameters*, but not the cstwMPC *model*.  The cstwMPC *model* is ConsAggShock or ConsIndShock, depending on whether it's the lifecycle or perpetual youth version.  cstwMPC is an *application*, not a model.

The demos there have little or nothing to do with cstwMPC itself, we just use the calibrated parameters from it.  They're there as top level demonstrations of HARK.

**Comment by mnwhite** [comment]
After an email exchange with CDC, I realized that our demos are not in fact in /Demos as I thought.  This was discussed with DCL a while back, but apparently never implemented.

The /ConsumptionSaving/Demos directory should be moved to be just /Demos, with path variables changed at the top of those files.

**Comment by mnwhite** [comment]
The /ConsumptionSaving folder now has *two* demo folders.

**Comment by mnwhite** [comment]
As of May 22, all of the Demos are being moved into Jupyter notebooks linked on econ-ark.org.  In the near future, the .py versions will be removed from the HARK repo.
