### ISSUE TITLE
pre-commit.ci

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1340]
We are currently using pre-commit (at least I am) to keep our code organized and following some basic standards. 

However, we don't enforce that any contributor install and run pre-commit or that new contributions meet the standards. 

Installing pre-commit locally and understanding what it's doing can be a bit taxing for new contributors. 

One way around this is https://pre-commit.ci/ which can still allow us to accept contributions from not fully experienced developers while still maintaining some basic standards in our code. This tool will create pull requests after new contributions and apply all fixes. 

Thoughts?

**Comment by MridulS** [comment]
> One way around this is https://pre-commit.ci/ which can still allow us to accept contributions from not fully experienced developers while still maintaining some basic standards in our code. This tool will create pull requests after new contributions and apply all fixes.

pre-commit CI will push new commits to the branch and then we need new contributors to pull in new changes before making any new commit to their branch and push it to github.

I would rather have us enforce pre-commit on PRs with a linting github action and ask the contributors to run `pre-commit install` locally.
