### ISSUE TITLE
Deep learning model estimation

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1345]
Once we have a general model language/object in HARK, and a robust monte carlo simulator (see #1296) it would be good to have a suite of estimation methods.

@JLDC has developed a "Deep Simulated Moments" technique (presented at DSE 2023) and is working on a Julia implementation.

It would be nice if HARK had a Python port of this method.

https://www.jldc.ch/publication/2023_deep-simulated-moments/
"Constructing Efficient Simulated Moments Using Temporal Convolutional Networks"
https://github.com/JLDC/DeepSimulatedMoments.jl

**Comment by JLDC** [comment]
Please let me know once you have the desired API, I'm happy to contribute a Python version of our networks.

**Comment by sbenthall** [comment]
Thank you very much! We will be in touch.

**Comment by akshayshanker** [comment]
Closing for as no immediate action relevant.
