### ISSUE TITLE
Package modules not included in standard install

### ISSUE THREAD

**Issue by sidd3888** [econ-ark/HARK#1353]
The modules in the HARK package that are described in the documentation as a package, for instance, ConsumptionSaving, are not being installed with either the `pip` or the `conda` install.

When I run `help(HARK)` I am able to see these modules listed, but when I try to import it using `import HARK.ConsumptionSaving`, I receive an error message that says HARK had no attribute named ConsumptionSaving.

- OS: Windows 11
- Tried on Python 3.9 and 3.10 with `econ-ark 0.13.0`
- Able to load the same modules when I clone this GitHub repo on my desktop

**Comment by alanlujan91** [comment]
@sidd3888 @MridulS I assume this was settled?

**Comment by sidd3888** [comment]
Yeah, it was entirely due to conflicts in the absence of a clean environment (even the anaconda default packages are bad news). Have incorporated this into the revised quick start guide. I shall promptly push that through.
