### ISSUE TITLE
Myst implicit targets not working locally

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1364]
I'm trying to build the documentation locally and am getting the following Sphinx error:

```
> sphinx-build -M html Documentation HARK-docs -T -W -j auto

...

sphinx.errors.SphinxWarning: /home/sb/projects/HARK/Documentation/guides/contributing.md:3:'myst' cross-reference target not found: 'code-of-conduct' [myst.xref_missing]
```

It looks like the configuration option for implicit targets in Myst is not set properly.
https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets

I'm not sure where this is set; how can it be included in the environment so that local compilation of the docs works?

**Comment by MridulS** [comment]
Hmm, I'm not able to reproduce this. Could you try upgrading all the libraries in your environment with something like `python -m pip install -U -r requirements/doc.txt` before building the docs?
What's the current sphinx version the build step is using?

**Comment by sbenthall** [comment]
This worked. Should have tried that first, of course. Thanks @MridulS
