### ISSUE TITLE
ImportError: cannot import name 'generated_jit' from 'numba'

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1382]
These errors are showing up on the continuous integration tests:

```
 ImportError: cannot import name 'generated_jit' from 'numba' (/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/numba/__init__.py)
```

What's going on? What depends on Numba?

**Comment by alanlujan91** [comment]
`AzureMachineLearning.ipynb` which uses `IndShockConsumerTypeFast`. Not widely used and we could remove from code base until we figure out what's going on with numba. 

`DecayInterp.ipynb` which uses `interpolation.py`. This might be required by @Mv77 and his JMP.

**Comment by mnwhite** [comment]
Alan thinks it's interpolation.py, which is not being maintained. I will go
through and see where we're actually using that and see if it can be
"unwound".

**Comment by alanlujan91** [comment]
The errors are below. All these files use `interpolation.py`

```
ERROR HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py
ERROR HARK/ConsumptionSaving/tests/test_PerfForesightFastConsumerType.py
ERROR HARK/tests/test_dcegm.py
ERROR HARK/tests/test_econforgeinterp.py
```

**Comment by alanlujan91** [comment]
https://github.com/EconForge/interpolation.py/issues/110

Need to set numba < 0.59.0
