### ISSUE TITLE
Module not found... numpy?

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1384]
<img width="529" alt="image" src="https://github.com/econ-ark/HARK/assets/5382704/b7670291-eace-4c4b-9575-644795b3cbb9">

Error says numpy is not installed, mamba (and conda) say it is installed and part of the env. 

this is my environment.yml file 

```
name: solvingmicrodsops
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - git+https://github.com/econ-ark/HARK@master
```

**Comment by alanlujan91** [comment]
I know enough about paths and terminals to break stuff, so this could be a local issue.

**Comment by mnwhite** [comment]
The condaforge thing is one of the outstanding elements of the version
update, as I had never worked with it at all. Was hoping to get Seb to help
me out today. I suspect this is related.

**Comment by alanlujan91** [comment]
@mnwhite I'm not sure if this would be related to conda-forge

This is installing python=3.10 from conda-forge, but using pip to install master branch of econ-ark. So when you see where numpy is coming from, it says it's from a pypi channel.

**Comment by MridulS** [comment]
Just tried this, works just fine for me?

Copied over the yaml config, then ran `mamba env create -f req.yml`.

```
$ mamba activate solvingmicrodsops
$ python -c 'import numpy; print(numpy.__version__)'
1.26.4
```

**Comment by Mv77** [comment]
I had this happen to me before and it was a weird issue with local VScode environments. This is probably not coming from the repo.

**Comment by alanlujan91** [comment]
Yeah I uninstalled and reinstalled Python and it worked!
