### ISSUE TITLE
What is update? How many terminal solutions?

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1405]
Looking at the `PortfolioConsumerType` I find the following `update` method:

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsPortfolioModel.py#L174

which calls RiskyConsumerType's update

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsPortfolioModel.py#L180-L181

which calls ConsIndShk's update

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsRiskyAssetModel.py#L87-L88

which finally updates the terminal solution.

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsIndShockModel.py#L1780-L1794

However, when initializing a PortfolioConsumerType, we instantiate the parent RiskyAssetConsumerType

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsPortfolioModel.py#L170

which instantiates the parent IndShockConsumerType

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsRiskyAssetModel.py#L73

which itself updates, and calls update_terminal_solution. So, this is the second call to update_terminal_solution

But we are not done.... 

PortfolioConsumerType has a pre_solve method

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsPortfolioModel.py#L176-L179

so this is the third time we're calling update_terminal_solution by my count!

If we are lucky, it's calling the same `update_terminal_solution` 3 times. I don't understand this enough but I *think* I have been in situations where, due to poor inheritance practices, the `update_teriminal_solution` that I expected is not the one being run, or at least not the last one being run. 

This is a big issue that sometimes makes debugging solutions harder than it needs to be.

**Comment by alanlujan91** [comment]
I think the solution is to remove the following lines 

https://github.com/econ-ark/HARK/blob/3ee397993a1db76bbc9ae24d3196dc31ccfe4874/HARK/ConsumptionSaving/ConsPortfolioModel.py#L174-L178

but this might not be the only model that does something like this

**Comment by mnwhite** [comment]
The good news is that as long as all of the classes are doing
`self.update_terminal_solution()`, they will call the right one. The bad
news is that we're doing redundant work. For the record, pre_solve is
probably the right place for it to be called (but update is often called by
pre_solve, so...?).

**Comment by alanlujan91** [comment]
Why don't we use super?

**Comment by mnwhite** [comment]
Because I don't think we want to use the parent class version at any point.
I could be wrong, however.

**Comment by alanlujan91** [comment]
No I mean in general, super at instantiation

**Comment by Mv77** [comment]
Yeah, this is a problem. I think some agent types run the "create income process" from ConsIndShock as much as 3 times each for a single solve. Which can take longer than the solve itself...

**Comment by Mv77** [comment]
Maybe a policy for this would be that every agent type should define (not simply inherit) its full `update`, `pre_solve`, and `post_solve` methods? You'd be free to call `super.update_whatever(...)` in them, but at least you would be doing it consciously?
