### ISSUE TITLE
HARKobject should inherit from object

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#141]
MNW believed that HARKobject was using "new style" methodology, but it is not.  HARKobject should inherit from object in HARKcore.py.

**Comment by edmundcrawley** [comment]
This change was made by MNW on the StickyE branch, which explains why he thought it had already been done. We can close this issue when the StickyE branch is merged into master.

**Comment by mnwhite** [comment]
Fixed with StickyE project merge.
