### ISSUE TITLE
Should pytest be a requirement?

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#1418]
The current test files import pytest, but pytest is not installed with hark. I wonder if it should be.

Do we consider the tests part of the package? If so, we should add pytest as a requirement.

**Comment by alanlujan91** [comment]
pytest is a development requirement, not a HARK requirement 

https://github.com/econ-ark/HARK/blob/master/requirements/dev.txt

**Comment by Mv77** [comment]
Cool, thanks. Closing

**Comment by Mv77** [comment]
I am not a smart man
