### ISSUE TITLE
Why does PerfForesightLabeled inherit from ConsIndShock?

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#1422]
The "labeled perfect foresight" model apparently inherits from `IndShockConsumerType` and thus expects a lot of information (about income shocks, etc) that has no meaning in the PF model. Why? I'm having a hard time updating the code because I need to get meaningless information into this class, or have it ignore that stuff.

**Comment by alanlujan91** [comment]
because IndShockLabeledType needs to import from IndShockConsumerType and PerfForesightLabeled, and I thought this was a good way to avoid multiple inheritance, which I still don't understand very well. 

If there is a better way to do it, then we should do that!

**Comment by mnwhite** [comment]
There's a better way. I am utterly baffled at how this class manages to initialize and run. It needs income shock parameters to be passed to it... but they're not in its default dictionary!

**Comment by alanlujan91** [comment]
they are in the parent's default dictionary!

**Comment by mnwhite** [comment]
They are not! This class inherits from IndShockConsumerType, but uses the perfect foresight dictionary as its default:

![image](https://github.com/econ-ark/HARK/assets/13963285/95f1647b-6027-42f5-aa3c-cd6bc632d363)

I'll check in a moment, but I suspect the explanation is that all of the tests are using a custom dictionary, not the default one.

**Comment by alanlujan91** [comment]
What is the default dictionary of IndShockConsumerType?

<img width="503" alt="image" src="https://github.com/econ-ark/HARK/assets/5382704/c9966b0f-8dd4-43bc-87e7-b1606a522e80">

**Comment by mnwhite** [comment]
Ok, I see now. Hopefully I can work it out.

**Comment by mnwhite** [comment]
This is now fixed in #1410 by manually re-adding the (unexpectedly needed) constructors. It's wonky because `update` is being run multiple times during initialization. In the future, I think we should work toward `update` or `construct` *not* being called automatically during initialization, and have the user do it manually.
