### ISSUE TITLE
Sequence Space Jacobian Notebook

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1435]
There are currently two PRs attempting to do the same thing. 

- #1416 
- #1424 

One issue with #1424 is that the `examples/HARK-SSJ-Example/ConsIndShockModel_HANK.py` file is mostly a copy of `ConsIndShockModel.py` with a few things changed. The approach I took in #1416 was to remove everything related to `ssj` and move it to its own file, while inheriting from `ConsIndShockModel` without repeating chunks of code. 

As far as I can tell, neither approaches work correctly yet, so I'm wondering if the authors could get together and figure out the best approach to get this through the finish line. 

@wdu9 @AMonninger @kennetheva

**Comment by mnwhite** [comment]
The notebook has now been merged into HARK and is working properly; it's currently being expanded and improved. Closing.
