### ISSUE TITLE
Problem with pip install econ-ark==0.14.1

### ISSUE THREAD

**Issue by edmundcrawley** [econ-ark/HARK#1437]
I get a dependency error when I try to install econ-ark 0.14.1 the version of interpolate. I uninstalled interpolate, but I still get the error. See error message below:

(py311) C:\Users\edmun\Downloads>pip install econ_ark==0.14.1
Collecting econ_ark==0.14.1
  Using cached econ_ark-0.14.1-py2.py3-none-any.whl.metadata (35 kB)
Requirement already satisfied: interpolation>=2.2.3 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (2.2.6)
Requirement already satisfied: joblib>=1.2 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (1.4.0)
Requirement already satisfied: matplotlib>=3.6 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (3.8.4)
Requirement already satisfied: networkx>=3 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (3.1)
Collecting numba<0.59 (from econ_ark==0.14.1)
  Using cached numba-0.58.1-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (1.26.4)
Requirement already satisfied: pandas>=1.5 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (2.2.1)
Collecting quantecon (from econ_ark==0.14.1)
  Using cached quantecon-0.7.2-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: scipy>=1.10 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (1.13.0)
Requirement already satisfied: seaborn>=0.12 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (0.12.2)
Requirement already satisfied: xarray>=2023 in c:\users\edmun\anaconda3\envs\py311\lib\site-packages (from econ_ark==0.14.1) (2023.6.0)
INFO: pip is looking at multiple versions of interpolation to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install econ-ark==0.14.1 and interpolation==2.2.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    econ-ark 0.14.1 depends on numba<0.59
    interpolation 2.2.6 depends on numba>=0.59.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by mnwhite** [comment]
Something's very odd here, because I'm 99% certain that we changed /
removed that version dependency in that release-- that was the point of it.
Let me look right now.

**Comment by edmundcrawley** [comment]
Update: I just tried with python 3.9 and it worked. Previously, when I got the error, I was using python 3.11.

**Comment by mnwhite** [comment]
Yes, the issue was with Python 3.11+, and it's now been resolved-- that's
why we had it restricted to 3.10 and lower. It looks like we forgot to
remove the numba restriction until last week (on a commit by Mridul).

I have one branch to merge in from Seb, and then will get to releasing
0.15.0. Note that to keep up with spec0, this will bump HARK's Python
compatibility to 3.10 *and higher*, so you can go right back to using
3.11... soon.
