### ISSUE TITLE
Example notebook has an error message

### ISSUE THREAD

**Issue by AMonninger** [econ-ark/HARK#1451]
**Describe the bug**
[LifecycleModel.](https://github.com/econ-ark/HARK/blob/master/examples/LifecycleModel/LifecycleModel.ipynb) notebook has an error message.

**Comment by mnwhite** [comment]
Does the error message appear when you actually *run* the notebook, or was it just mistakenly saved with an error showing? This notebook is tested automatically, so it should run properly.

**Comment by DominicWC** [comment]
It runs properly when it's downloaded. It was probably saved after being run with an older version of HARK, which should be fixed. That being said, it doesn't run on Binder. It throws a `ModuleNotFoundError: No module named 'EstimationParameters'` error.
