### ISSUE TITLE
Econforge interpolation tests are failing

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#1458]
Without making any changes to our code, Econforge interpolation is now failing; see #1457 for what's going on.

Assigning Alan because I have no idea how Econforge works or what it's being used for in HARK.

**Comment by mnwhite** [comment]
The issue was numba going to 0.60.0 on June 13. I have now pinned it to 0.59.1, the prior version. We might want to instead put it as < 0.60.0.

**Comment by albop** [comment]
Hey @mnwhite, I'll have a look at what changed in numba recently and get back to you
