### ISSUE TITLE
Broken Documentation links

### ISSUE THREAD

**Issue by DominicWC** [econ-ark/HARK#1476]
**Describe the bug**
The Pull request which removes symlinks and adds extra example notebooks also changes some of the documentation links. This means some hard-coded links now go nowhere. This also means that opening the notebooks on binder doesn't work at the moment.

PR #1470 already has fixes for this, but parts of that PR are still in development. A fix will also have to be pushed to the econ-ark website.

I'm leaving this open until the issue is fixed in HARK and on the econ-ark website.

**Comment by mnwhite** [comment]
Dominic made a separate PR to fix this.
