### ISSUE TITLE
ConsIndShock: cFunc extends below mNrmMin

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#155]
A student at Goethe University flagged this issue for us.

The consumption function in ConsIndShockModel exists below mNrmMin, but it should not.

Explanation: cFunc is a LowerEnvelope instance containing cFuncCnst and cFuncUnc.  cFuncCnst hits zero and ceases to exist at mNrmMin, but cFuncUnc continues further down to BoroCnstNat.  LowerEnvelope uses nanmax rather than max, so it throws out the nan from cFuncCnst and thinks it should use cFuncUnc below mNrmMin.

Solution: Add optional boolean input for LowerEnvelope (and related classes) to indicate whether to use max/min or nanmax/nanmin.  Default should be nanmax.

**Comment by TimMunday** [comment]
I will have a PR coming on this in the next couple of days.

**Comment by mnwhite** [comment]
Awesome, let me know if you need help / get stuck.  Hopefully the description above is enough.

Just to clarify, the optional input here would be for the `__init__` method, not `_eval` (or whatever it's called).  That is, the boolean is an object attribute, not an optional input when you want to query the interpolation.
