### ISSUE TITLE
FashionVictim should be converted to a Jupyter notebook

### ISSUE THREAD

**Issue by lucamazzone** [econ-ark/HARK#165]
It would be a great way to illustrate the aggregation tool for students.

**Comment by llorracc** [comment]
Thanks Luca.  I've marked this is a "help wanted" project and hope someone will do it for us!

**Comment by mnwhite** [comment]
We have only just got started building notebooks. We will definitely make a
FashionVictim notebook to use as our "learn Market with no economics"
lesson notebook.

**Comment by mnwhite** [comment]
To clarify: This notebook will be in a different repository where we keep teaching / instructional / lesson notebooks.

The first notebook of this sort is the Gentle Introduction to HARK, which will be moved from DemARK to the teaching repository.

**Comment by mnwhite** [comment]
Should have closed this a while ago, as notebook from YMCankus exists now.
