### ISSUE TITLE
Add Portfolio Choice to ConsIndShockModel

### ISSUE THREAD

**Issue by econ-ark** [econ-ark/HARK#166]
At present, the only asset in which the consumer with uncertain income can invest is one that earns a safe rate of return Rfree.  A common extension of this model (indeed, the foundation for the asset pricing literature) is to allow the consumer to make a choice of how much of their portfolio to invest in a risky asset, usually calibrated to match characteristics of returns on the stock market.  This has already been done in [the lecture notes](http://econ.jhu.edu/people/ccarroll/SolvingMicroDSOPs/) that were the original source for implementing ConsIndShockModel -- but the associated code in [the source archive](http://econ.jhu.edu/people/ccarroll/SolvingMicroDSOPs.zip) was written in Mathematica.  Translating that into the HARK way of doing things (with a bit of guidance from us) would be a useful contribution.

**Comment by mnwhite** [comment]
See issue #114.
