### ISSUE TITLE
In HARK/cstwMPC do we need cstwMPCold?

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#179]
I'm guessing from the "old" suffix that it can be removed?

**Comment by mnwhite** [comment]
I keep meaning to look into that. I know it doesn't run anymore, but
haven't deleted it in case there's an odd bit of code that didn't get moved
to the new version. Maybe some robustness checks and figures?

**Comment by pkofod** [comment]
This can be closed I think
