### ISSUE TITLE
Error in ConsIndShockModel when run as non-package

### ISSUE THREAD

**Issue by edmundcrawley** [econ-ark/HARK#182]
When you run ConsIndShockModel by typing:
run ConsIndShockModel
in Spyder, you get an error:

    from . import ConsumerParameters as Params
ValueError: Attempted relative import in non-package

This error occurs when the code at the very end of the file is run:

if __name__ == '__main__':
    main()

This code is not normally run when the file is used as a package. I'm told that perhaps I should not be running this code as a non-package now, but if that is the case these lines of code at the very end should probably be removed. If not removed, then the bug should be fixed.

Nathan suggests that OTS will have some useful input on this point.

**Comment by mnwhite** [comment]
Fixed, forgot to close issue.
