### ISSUE TITLE
Description of "Beth" in TractableBufferStockModel?

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#183]
Maybe this could be slightly more informative? :)

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/TractableBufferStockModel.py#L108-L109

**Comment by mnwhite** [comment]
This issue is duplicative of #36 , which has been outstanding for over two years.

**Comment by pkofod** [comment]
Alright, closing then :)
