### ISSUE TITLE
Revamp library API

### ISSUE THREAD

**Issue by brainwane** [econ-ark/HARK#191]
As @jvasile noted:

> The current API is an ad-hoc collection of methods for accessing Econ-ARK's diverse array of analytical offerings. A mature library would feature a coherent API that adheres to consistent conventions around naming, types, structure, parameter order, return values, error-reporting and the like. We need to
> (a) survey the current set of APIs for existing (and divergent) conventions;
> (b) establish and document one convention for use across all APIs; and
> (c) adjust the existing APIs to conform to this standard; while
> (d) providing a backwards-compatibility path for old code.

**Comment by brainwane** [comment]
@albop I'm looking forward to discussing this with you -- maybe Monday?

**Comment by albop** [comment]
@brainwane : sure, I can do next week after Wednesday
