### ISSUE TITLE
Which Interest Factor is used with the KinkedR Consumer Type

### ISSUE THREAD

**Issue by nomadj1s** [econ-ark/HARK#196]
I have a question about the `calcEndOfPrdvP` method, that is defined under the `ConsIndShockSolverBasic` solver. At approximately line 840, we have the following code:
```python
EndOfPrdvP  = self.DiscFacEff*self.Rfree*self.PermGroFac**(-self.CRRA)*np.sum(
                      self.PermShkVals_temp**(-self.CRRA)*
                      self.vPfuncNext(self.mNrmNext)*self.ShkPrbs_temp,axis=0)
```
This method is inherited by the `KinkedRSolver`, however it uses the `self.Rfree` interest factor. Is this supposed to use the `self.Rboro` or `self.Rsave` interest factors instead when we are using a KinkedR model?

Thanks,
Damon

**Comment by mnwhite** [comment]
Yes, this solver uses `Rboro` and `Rsave` correctly when computing `EndOfPrdvP`.  See `ConsKinkedRsolver.prepareToCalcEndOfPrdvP` where `self.Rfree` is defined as a vector with each element equal to `Rboro` or `Rsave'.

In the line you pasted above, everything to the right of `self.Rfree` is a vector (of size `aXtraGrid.size`), so it can be multiplied by either a vector of the same size (in KinkedR) or a constant (in the basic model).

**Comment by nomadj1s** [comment]
Oh yes, I see it now. I don't know how I missed that. 

Thank you.

**Comment by mnwhite** [comment]
No problem.
