### ISSUE TITLE
Using HARK in graphical environments or working around it

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#199]
Just tried to install on an AWS EC2 instance, and on trying to use it got the error "HARK must be used in a graphical environment."  

In fact, there are a number of ways in which someone might want to use Econ-ARK/HARK tools without a graphical front end.  Most notably, someone might want to offload some compute-intensive stuff to AWS or another platform, let it run and generate results, and then collect those results.  This could even include figures; matplotlib can be used without a graphical environment (the figures do not render but can be saved).  

A test case would be to run any of the `do_min.py` files in the [REMARK](https://github.com/econ-ark/REMARK) repo.  These should be executable from within the appropriate directory just by the command-line command `ipython do_min.py` -- which has been tested and found to work on full-blown systems.  (A good choice might be [BufferStockTheory/do_min.py](https://github.com/econ-ark/REMARK/blob/master/REMARKs/BufferStockTheory/BufferStockTheory.py)).

However, it would also be useful to know how someone who DOES want to use interactive graphical tools in HARK could set up a VM that would satisfy whatever are the 'graphical environment' requirements.  (I found that installing the full-blown Ubuntu/Xubuntu desktop was sufficient, but unclear if necessary -- and it took a while to figure out how to do that).

**Comment by MridulS** [comment]
I can look into this.

**Comment by llorracc** [comment]
Great -- the goal is basically to make it easy for people not very familiar with AWS or Google Compute Platform to spin up a VM that can be used with all the graphical tools of HARK.  A script or how-to is what is needed.

**Comment by sbenthall** [comment]
Can this issue be closed?

**Comment by MridulS** [comment]
Yeah, all good now.
