### ISSUE TITLE
__name__ == 'main'

### ISSUE THREAD

**Issue by dclow** [econ-ark/HARK#2]
If at all possible, every .py file should have:

if __name__=='__main__':
    (example code showing what the file does)

Ideally this would both show off the capabilities of the code and demonstrate how to use it.  None of the .py files have this so far it seems

**Comment by mnwhite** [comment]
Done in latest commit to comments-and-cleanup.  Every module now does *something* when run, but in many cases it just prints a message pointing the user to a more interesting module that uses this one.
