### ISSUE TITLE
Docstrings: mention mutation?

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#202]
I generally try to follow the docstring-style in the rest of the toolkit when writing code, but I have a question and/or a suggestion with regards to mutation of variables in functions.

Say I have a funtion
```
def f(x, i):
    """
    f does something related to some economic problem.

    Parameters
    ---------------
    x : numpy.ndarray
        some economic variable we are interested in working with
    i : integer
        some index of the relevant part of x
    
    Returns
    ----------
    Nothing
    """
    x[i] = 0
```

This seems to follow the general style in the toolkit. I was wondering if it'd make sense to have a
```
    Mutates
    ----------
    x : numpy.ndarray
        has it's i'th element set to zero
```
section, such that the reader can quickly realize that `f` is not a pure function, since it has the side-affect that `x[i]` is changed.

**Comment by mnwhite** [comment]
If you're going to have a function that does this, I think it's better to have it as a method of that object's class, not as a function.

If you have a function that "mutates" one of its inputs, my preference is that you have it return an altered copy of that input, not operate on the input itself.  Otherwise, your function essentially "throws out" its input, and that's usually not how I think of a function.  A method of a class is more appropriate when this operation is acting on itself.

**Comment by pkofod** [comment]
> If you're going to have a function that does this, I think it's better to have it as a method of that object's class, not as a function.

I see what you're saying. The only problem is that if we want to use numba or an alternative (and we really do sometimes if we want to keep stuff in python), we're going to have to write some of these methods as simple wrappers over jitted functions, since jitclasses are a PITA imo. This means that somewhere in the code base there's going to be a function that has side-effects (like mutating a variable like my example), but do not mention it in the docs. In the wrapper function it might be clear what's going on, but maybe not.

> If you have a function that "mutates" one of its inputs, my preference is that you have it return an altered copy of that input, not operate on the input itself.

Depending on the degree to which things like the G2EGM re-interpolate-and-upper-envelope-step is written as several functions instead of one big function with 20 indents, this might be a lot of copying. But I guess some of this can be fixed by thinking about some of these things differently.

> Otherwise, your function essentially "throws out" its input, and that's usually not how I think of a function. A method of a class is more appropriate when this operation is acting on itself.

You mean a mathematical function or a function in a programming sense? I don't think it's too uncommon to use this kind of pattern to avoid allocating memory (say by copying), say using subroutines in Fortran. If you're talking in a Python sense, then sure, I see what you mean. I guess it's a cost of "leaving Python mode" that some design patterns change once you want to add numba to the mix.

> A method of a class is more appropriate when this operation is acting on itself.

Yes, I'll see if I can use wrappers to make this clear whenever I stumble upon such a case as the one I mentioned in the beginning. It still means that there's going to be a jitted function somewhere in the file or toolkit that actually does mutate its input, but might not say so in a clear manner. I guess it can still be mentioned in the body of the docstring even if it doesn't have a header such as the one I suggested above.
