### ISSUE TITLE
Post-solution figures and post-simulation data

### ISSUE THREAD

**Issue by nomadj1s** [econ-ark/HARK#203]
Is there any code demonstrating:

1. How to export the figures after using plotFuncs. After the command is run, it seems like the figure is no longer in the memory.

2. How to make plots using the results of the simulations? In particular, for lifecycle simulations, is there an easy way to track a panel id variable? I can see how I can track t_age and collapse data by age, but who would I track individual agents within the simulation?

I can probably come up with solutions, but was just wondering if there is already code existing that I can build off of.

**Comment by mnwhite** [comment]
Figures can't be exported to file using plotFuncs.  We added plotFuncs and plotFuncsDer as a quick-and-easy way to look at 1D functions.  If you want to make a figure to save to a file, you have to manually construct it with matplotlib (or another plotting package), then save it.  In matplotlib.pyplot, the function plt.savefig(filename_or_path_as_string.extension) will save the figure in the format you want.

I'm not sure what you exactly mean by "track a panel id variable".  It sounds like you know how to use track_vars.  Can you be a bit more explicit in what information you want to extract?

**Comment by nomadj1s** [comment]
Suppose I simulate 100 agents for 10 periods. I want to be able to track each agent `i`. The `t_age` variable tracks time, but is there a variable that can track individuals over time?

For example, suppose I want to know how consumption evolves after a large negative shock in period `t`. I could focus on all the agents who drew negative shocks in period `t`. But in order to track subsequent consumption just for these individuals, I'd need to have some index `i` to link tracked variables over time, if that makes sense.

**Comment by mnwhite** [comment]
Ah, I was wrong to assume you knew about `track_vars`.  Each instance of `AgentType` subclasses has an attribute called `track_vars`, a list of strings that name attributes whose "history" (on an agent-by-agent basis) should be tracked.  For example, you can do:

```
ThisType = IndShockConsumerType(**some_dictionary)
ThisType.AgentCount = 10000
ThisType.T_sim = 200
ThisType.track_vars = ['cNrmNow', 'aNrmNow']
ThisType.initializeSim()
ThisType.simulate()
```

That will simulate 10,000 agents for 200 periods.  `ThisType` will have attributes called `cNrmNow_hist` and `aNrmNow_hist`, which are both arrays of shape (200,10000) with the history of normalized consumption and end-of-period assets for all of the agents.

Important: If you're doing a lifecycle model, or really any model with death in it, note that the simulation will *kill and replace* agents as it goes.  So `cNrmNow_hist[:,138]` won't necessarily have 200 periods of exactly one agent, Mr 138, but also each agent who has lived in Mr 138's house after he dies (so to speak).

**Comment by mnwhite** [comment]
It is one 2D array for each simulated variable.
