### ISSUE TITLE
Restricting parameter space (throwing errors, warning, etcs)

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#204]
If someone (well, that me right now, but in general) wants to add a model somewhere in econ-ark and implement a solution method that only works for some parameter combinations (say some relation between the discount factor and a risk free return). Is there an agreed-upon way to catch and handle such exceptions in econ-ark?

**Comment by mnwhite** [comment]
If it's something like the example you gave, where the parameter restriction violation can be caught outside of / before the solution method (i.e. it isn't a problem that is only revealed after solving X periods; it can be determined ex ante), then:

My preference is for there to be a class method that is called during preSolve(), which evaluates the restriction and either a) prints to screen something like, "blah is greater than bloo, which the solver is not able to handle.  You should expect the solution produced by solve() to be incorrect, or to crash." OR b) does that, but as an assertion error or raised exception.  You can also call this parameter check method from update(), which is called by preSolve() in most models, and is also called during __init__.  If you do that, definitely just print the message to screen, don't throw an exception or assertion error; we want the instance to be created, in case the user wants to do something with it other than solve.

**Comment by mnwhite** [comment]
If you look at ConsIndShock and PerfForesight, there are methods written by one of Chris' students that check the variations of the impatience condition when relevant (T_cycle = 1, cycles = 0), and report violations.  I think Chris favors this approach.

**Comment by llorracc** [comment]
There is a branch, "Fix-Impatience-Tests", which I have never submitted a pull request for, which updates the earlier work done by my student.  If you could look at that branch and clean it up and submit a pull request, that would be great.

**Comment by pkofod** [comment]
Thank you for the answers. I’ll finish up that branch and make a pr

**Comment by pkofod** [comment]
> Thank you for the answers. I’ll finish up that branch and make a pr

This PR was made and merged, but what remains to be done here is to add a check for a fatal parameter specification (negative when it's supposed to be strictly positive for example) and test it on travis.
