### ISSUE TITLE
Interpolants vs interpolation functions

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#210]
cc @albop @mnwhite 

I understand that work is being done to interpolations (in the actual evaluating a function off-of a few know grid points kind of interpretation) in HARK.

I was curious if there were any plans/thoughts/... on whether to provide either interpolant objects-style interpolation
```
inter = SomeInterpolant(xs, ys, ...)
interpolated_values = interp(new_xs)
```
or function style interpolation
```
interpolated_values = some_interpolation_method(xs, ys, ...)
```
or possibly both, with the interpolant `__call__`ing into an interpolation function you can also just access yourself.

I'm asking because I can totally see the reason why some users might like the interpolant. It reads a bit more like "math".

However, I often find it simpler to reason about passing around arrays and interpolating where needed based on those arrays. In a recursive model you often only need the interpolant one or two times anyway, so in my personal view interpolant objects can often be over-engineered solutions for the problem at hand - with the possible exception if you easily want to plot, evaluate, etc after you're done solving the model.

Thoughts, counter-points, plans? I'm curious! :)

**Comment by albop** [comment]
@pkofod : the premise that you need the interpolant one or two times only is not quite accurate. You require it many times, when you need to solve for the decisions today as a function of tomorrow's decisions and can't apply a closed form formula. Also when you simulate. 
Granted, for linear/multilinear interpolation it makes no difference because there is nothing to precompute but for all other kinds of interpolation (splines, rbfs...) there is a special function representation which needs to be stored. Believe me, this is not a second order optimization.

Due to limited compatibility of python objects with jit, the current plan in interpolation.py is to store this interpolant in a structure-like object ala Julia (for now a nested-tuple structure, without methods). So the call above would be more like:
```
itp = SomeInterpolant(xs, ys, ...)
interpolated_values = interpolate(itp, new_xs)
```
It is fairly trivial to make object wrappers in HARK around interpolants to implement the `__call__` function. Fairly trivial too to make a flat call function `interp = lambda s,x,v: Interpolator(s,x)(v)` or something like that, but I don't think it is a good idea (for perf. reasons).

**Comment by pkofod** [comment]
> the premise that you need the interpolant one or two times only is not quite accurate.

Depends on the use, but I know that it doesn't cover all use-cases. That's why I was interested in the direction the project is headed. I'm already using the class+`__call__` style provided by HARK.

> when you need to solve for the decisions today as a function of tomorrow's decisions can't apply a closed form formula.

do you mean like numerically solving an Euler equation with a rootfinder that needs to interpolate at different values? Can't see why a function call can't be just as efficient as a class with a `__call__` method. Especially given the boiler plate code involved in numba jitted code (I don't know Cython etc, so don't know how it applies to those).

> Also when you simulate.

You mean interpolating the policies at some states?

Anyway, it's sort of tangential, I know that there are many cases where you need to interpolate repeatedly. Doesn't really explain why it should be in a class, and certainly not with the current boiler plate needed for `jitclasses` - in my opinion!

> Due to limited compatibility of python objects with jit, the current plan in interpolation.py is to store this interpolant in a structure-like object ala Julia (for now a nested-tuple structure, without methods). So the call above would be more like:

> Granted, for linear/multilinear interpolation it makes no difference because there is nothing to precompute but for all other kinds of interpolation (splines, rbfs...) there is a special function representation which needs to be stored. Believe me, this is not a second order optimization.

I know! In a project unrelated to HARK [though it could be in HARK] we're solving multidimentional models on tensor products of univariate grids (yes, they unfortunately have to be for theoretical reasons), and not calculating and saving the factorized matrices up front would kill the performance. I'm fine with either way as well, was just curious if the plan was to support one-off calls to interpolating functions. Seems like it's not on the table / a priority.

> It is fairly trivial to make object wrappers in HARK around interpolants to implement the `__call__` function.

I guess that would be fine for vectorized calls, though not if you want to jit the function that needs to interpolate.

Anyway, I'm looking forward to the improvements !

**Comment by llorracc** [comment]
Responding to albop's comment above, I strongly endorse the function approach.  There could be many kinds of info that you want to compute and store in the function.  I'm a big fan of the way Mathematica does this with its 'InterpolatingFunction' objects.

**Comment by pkofod** [comment]
While work continues on the interpolation features and dependencies in HARK, I've closed this issue. I originally opened it after having written some code where an interpolant provided no extra value over having an `extrapolate(from_these_xs, from_these_values, to_these_xs)` interface, but I do realize that there are many other situations where an interpolant is much more convenient. One example is re-use of the same points and values to interpolate onto values several times, or where you want to expose the interpolant to the end-user as part of the solution for example.

So I'm closing this, as there are no outstanding, actionable steps or issues left to discuss or tackle.
