### ISSUE TITLE
FashionVictim Import Error

### ISSUE THREAD

**Issue by rabideaub** [econ-ark/HARK#211]
The FashionVictimModel.py code results in an error when run. The error messages is as follows: 
ImportError: cannot import name 'FashionVictimParams' from '__main__'

The error appears to be in line 18:
from . import FashionVictimParams as Params

The code runs correctly when the program is updated to specify the import directory as:
from HARK.FashionVictim import FashionVictimParams as Params

**Comment by llorracc** [comment]
Thanks.  I've tagged @npalmer-professional on pull request #212 which fixes this.

**Comment by mnwhite** [comment]
I merged it in.
