### ISSUE TITLE
Why not expose the factors?

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#220]
When an example of an infinite horizon IndShockConsumerType is instantiated, various "factors" are calculated (like, the "Growth Impatience Factor").  Some of these calculations involve taking expectations, and so are not computationally costless.  The code reports to the user the implications of some conditions on the factors (and more can be obtained using the checkConditions() method), but once these calculations have been done the factors are discarded.  Why not expose them to the user as attributes of the instance?

**Comment by mnwhite** [comment]
It can definitely be done. The only reason I can think not to is that these
terms aren't commonly known, so the attribute GIC or
GrowthImpatienceCondition might not be understood.

**Comment by llorracc** [comment]
OK, when we update checkConditions to return the factors, we should add info about where to look up detailed descriptions of the conditions and their implications.

**Comment by llorracc** [comment]
I've done a version of this, but need to turn it into a PR.

**Comment by sbenthall** [comment]
@llorracc any progress on this?
