### ISSUE TITLE
Document consumer solution sequence

### ISSUE THREAD

**Issue by kchipeniuk** [econ-ark/HARK#223]
Recently, while familiarizing myself with HARK, I found it challenging to excavate the sequence of function calls which solves one period of a consumer’s problem in ConsIndShockModel.  In my particular case, I wanted to access the endogenous grids generated during the solution, which all told required the following steps:

1)	Create an instance of ConsIndShockSolverBasic
2)	Call prepareToSolve from the parent class ConsIndShockSetup
3)	Call prepareToCalcEndOfPrdvP
4)	Call calcEndOfPrdvP
5)	Call getPointsForInterpolation

I have my bearings now, but it could help future contributors become acclimatized if there were documentation/example code which maps out the procedure for solving the single period problem.

**Comment by mnwhite** [comment]
If by "the endogenous grids generated during the solution", you mean the normalized market resources (mNrm) and consumption (cNrm) values used to construct the consumption function, these can be more easily accessed as `KarstensInstance.solution[t].cFunc.functions[0].x_list` and `KarstensInstance.solution[t].cFunc.functions[0].y_list` respectively.

But in general, yes: The solution code is a bit of a maze, and there is no "map" that explains the structure of the methods, and which methods are overwritten by which child models.  This is something I'm going to work on this semester.

Eventually, there's going to be a complete overhaul / redo of the various solvers to give them better structure.

**Comment by kchipeniuk** [comment]
Thanks - helpful to know the grids are returned as part of the consumption function.  

Good to hear there are plans for mapping/eventual overhauling, as well.

**Comment by pkofod** [comment]
I guess there could be a sort of "How we solve a period" DemARK of the relevant steps. I was actually taking notes to do such a DemARK, because I've been touching more and more of the existing code and internals. However, if many things stand to change soon, this might be premature and a waste of time. After an overhaul, such a DemARK would be an excellent resource for newcomers who want to contribute to HARK, I think.

**Comment by shaunagm** [comment]
MNW will pull in Tiffany's notebooks and add missing sections, once that's merged into our Demarks repo, we can close this issue.

**Comment by sbenthall** [comment]
The HowWeSolve notebook is now in `examples`:
https://github.com/econ-ark/HARK/blob/master/examples/HowWeSolveIndShockConsumerType/HoweWeSolveIndShockConsumerType.ipynb

 Closing
