### ISSUE TITLE
Breaking changes from version to version

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#232]
Has there been any discussion on how to handle breaking changes to things like keyword/parameter names, output from functions (a function might have returned 1 and is now returning 2 outputs), and so on?

Are the current releases allowed to simply break as they please, or is it the intention that tools such as https://pypi.org/project/deprecation/ should be used?

A situation could be one like all of the conditions checks that were added. With them, there were quite a few variables that were renamed as far as I can remember. If users have code that relies on these variables, their code might fail after HARK is updated.

It might not be a concern yet if you consider the software "alpha", but even to the "alpha", "beta" and "release-candidate" users, this can be a source of much frustration if not handled with care.

Anyway, this is just to start a discussion because I havn't seen anything like it in relation to HARK, but I know from past experience that it can really ease user transition from version to version, even if those versions adhere strictly to semver 2.0.

**Comment by shaunagm** [comment]
Hi @pkofod!  I'm closing this issue and copying your comment over to [Implement new release system #4](https://github.com/econ-ark/OverARK/issues/4) over on our new project management repo.
