### ISSUE TITLE
On the Testing folder

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#246]
So, I just opened https://github.com/econ-ark/HARK/pull/245 to clean up a file in the Testing folder as per recent discussions.

I wanted to touch on the rest of the files here.

1) https://github.com/econ-ark/HARK/blob/c394d0f779e78ba89081510cde6c0253b4dcfdc1/Testing/Comparison_UnitTests.py
This one is fit for inclusion in the `HARK\tests` folder I think. Solves some models and compares them in a meaningful way

2) https://github.com/econ-ark/HARK/blob/c394d0f779e78ba89081510cde6c0253b4dcfdc1/Testing/ModelTesting.py
Work in progress (?) that seems to test the behavior depending on what parameters are input to the models. Seems fit for `HARK\tests` but it's not clear to me that it's finished.

3) https://github.com/econ-ark/HARK/blob/c394d0f779e78ba89081510cde6c0253b4dcfdc1/Testing/MultithreadDemo.py
Not a test, but a demo of multhreading in python? Maybe move to DemARK to show how to use multithreading to quickly solve many variants of a given model on modern CPUs that often have many cores/threads.

4) https://github.com/econ-ark/HARK/blob/c394d0f779e78ba89081510cde6c0253b4dcfdc1/Testing/TractableBufferStockModel_UnitTests.py
Tests the consumption function against a hardcoded solution vector. May be directly transferable to `HARK\tests`, but we should probably be quite sure where that vector comes from. Is it just the solution that was there when the file was generated, put in place to avoid changes in behavior of the solution? Or is it meant as some sort of validation against an externally generated (external to HARK that is) solution?

**Comment by shaunagm** [comment]
@pkofod, can you @ or assign to whoever you'd like to reply to this/review this?

**Comment by pkofod** [comment]
Okay, yes.

1)  @pkofod 
2) @mnwhite the idea here is to just try to solve the model for many values of parameters, right? We can use CI to test for errors thrown, or we can test for values of the solutions, but it's not 100% clear to me what the idea is with these tests
3) This does not seem to be a test at all, it's more of a DemARK, right ? @mnwhite states in the initial commit:
```
Three TBS testing files by DCL have been moved into /Testing, along with
MultithreadDemo (which is sort of a test, and doesn't really fit
elsewhere).  These files probably don't work now due to path changes,
will fix later today.
```
4) @pkofod

**Comment by mnwhite** [comment]
I'm not sure I wrote any of those files other than MultithreadDemo, which (yes) should be in DemARK.  The other files look like efforts by David Low and/or Nate Palmer to put testing in HARK.  They might be better suited to answer Qs about 1 and 2.

The message you reference is only the initial commit on MultithreadDemo.py because that file used to live elsewhere.

**Comment by pkofod** [comment]
> The message you reference is only the initial commit on MultithreadDemo.py because that file used to live elsewhere.

I figured. I'm adding 1 and 4 to the folder CI can find, and then I'll take a closer look at 2. 3 should either go to the cemetery or moved to DemARK.

**Comment by pkofod** [comment]
For a potential sprinter, you may want to find/contact @llorracc (unless he has already written something here by then). Most of the files are handled here, but we still need to figure out what to do with the second file. @npalmer-professional may have something to say about the intent of those files, and how they might be turned into tests of predictable behavior so they are suitable for CI.

**Comment by llorracc** [comment]
This is connected to  issue 18 in the OverARK: https://github.com/econ-ark/OverARK/issues/18 which proposes that we use existing DemARK and REMARK .py files as fodder for Travis.

**Comment by shaunagm** [comment]
This is connected two issues in the OverARK repo, [#18](https://github.com/econ-ark/OverARK/issues/18) which discusses our general plan for unit testing and [#29](https://github.com/econ-ark/OverARK/issues/29) which talks about using existing DemARK and REMARK .py files as fodder for Travis.

@llorracc @pkofod @mnwhite, can you make sure I've got the plan for this correct?

As I understand it, 1 and 4 are taken care of, 2 is being turned into a unit test, and 3 is being turned into a demark/remark?  Can sprinters help with both 2 and 3?

**Comment by pkofod** [comment]
`Testing` exists no more!
