### ISSUE TITLE
Fix stylistic issues in HARK

### ISSUE THREAD

**Issue by shaunagm** [econ-ark/HARK#262]
We've adapted flake8 for "code linting", as per issue #171.  Now we need to use flake8's output to make our code more pythonic.  This is a great issue for newcomers who want to get familiar with our codebase.  

To run flake8, make sure you've installed the requirements in requirements.txt (or simply type `pip install flake8`) and then run in your command line/prompt `flake8 HARK/core.py`, substituting the relative path is to the file you want to lint.

I've broken out the codebase into sections so multiple people can tackle this issue at once.  If you'd like to grab a section, comment below.

- [ ] top level HARK folder (core.py; dcegm.py; estimation.py; interpolation.py; parallel.py; simulation.py; utilities.py
- [ ] tests folder
- [ ] ConsumptionSaving folder
- [ ] FashionVictim folder
- [ ] SolvingMicroDSOPs folder
- [ ] cAndCwithStickyE folder
- [ ] cstwMPC folder

**Comment by StephenSchroeder** [comment]
I was thinking I will start off by linting the tests folder!

**Comment by rsaavy** [comment]
I will be working on pylinting on core.py

**Comment by StephenSchroeder** [comment]
I just finished linting the Testing folder, and I will continue linting the tests folder (within the HARK folder which is probably where the linting was meant to be done anyways)

**Comment by llorracc** [comment]
Awesome, thanks!  I guess @shaunagm probably should be the one to merge the PR's since she is on the spot (and knows more about this than we do anyway!)

**Comment by rsaavy** [comment]
I'm working on dcegm.py 

I ran into this error for flake8 

`dcegm.py:155:25: E712 comparison to False should be 'if cond is False:' or 'if not cond:'`

**Comment by llorracc** [comment]
Patrick has probably gone to bed (I think it's midnight now in Copenhagen) so he can look at this tomorrow.  

(I'm new to flake8.  My guess about that message was that it referred to what it thought was a problem on line 155 (not sure what the '25' was), but line 155 is `    upperV_T = np.zeros(m_len)` which does not seem related.  Maybe it is actually identifying line 158, which reads:

`upperV_T[row_all_nan == False] = np.nanmax(commonV_T[row_all_nan == False, :], axis=1)`
?

**Comment by rsaavy** [comment]
Hi,

Line 155 for me after I had removed some lines is 
`    idx_max[row_all_nan == False] = np.nanargmax(commonV_T[row_all_nan == False], axis=1)
`

**Comment by llorracc** [comment]
Hmm, so do you think it is suggesting 

`upperV_T[if row_all_nan is False] = np.nanmax(commonV_T[if row_all_nan is False, :], axis=1)`

?  That looks odd to me.

**Comment by rsaavy** [comment]
I've linted most of it the smaller issues:

The errors 
`dcegm.py:155:25: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dcegm.py:161:26: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dcegm.py:175:50: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
`

I will make PR so you can see which lines those are

**Comment by shaunagm** [comment]
So it seems to be complaining that we're confusing "falsy" with "false".  In Python, "falsy" values are any values where `bool(value)` returns `False`, for instance `False`, `[]` and `None` are falsy, while only `False` is false.  "If not cond" is saying, "if cond is falsy", whereas "if cond is False" is saying "if cond is False".  It wants us to determine if `cond` should be falsy or false.  Can it be a `[ ]` or a `None` or can it only be `False`?

**Comment by llorracc** [comment]
OK, that makes sense.  But I don't know the answer -- we'll have to wait for @pkofod

**Comment by mnwhite** [comment]
It looks to me like we can't use "cond is False", because cond is a
(boolean) array, not just a single bool.  You definitely can't put an if
statement inside indexing brackets.  I would write this line as:

valid_rows =  np.logical_not(row_all_nan)
upperV_T[ valid_rows   ] = np.nanmax(commonV_T[ valid_rows   , :], axis=1)

**Comment by shaunagm** [comment]
FYI Ingrid & I are grabbing estimation.py to lint.

**Comment by michiboo** [comment]
Hi I will take SolvingMicroDSOPs folder

**Comment by sbenthall** [comment]
Since this issue has been made, we've converged now on `black` for linting/styling.

I wonder if we should make run this as the final step before the 0.10.7 release.
The problem with this change is that because it touches all the files, it's hard to do when there's a lot of ongoing work in PRs.

What do you think, @MridulS ?

I think we may also be waiting for more definite buy-in from @llorracc and @mnwhite on this.

**Comment by MridulS** [comment]
We use `black` now. :)
