### ISSUE TITLE
Installation Instructions Incomplete for Windows

### ISSUE THREAD

**Issue by aawalker9** [econ-ark/HARK#263]
Instructions for how to activate a virtual environment only work on Linux, not Windows. 
C:\PythonPlus\64bit\pkgs>virtualenv econ-ark
C:\PythonPlus\64bit\pkgs>econ-ark\Scripts\activate.bat

**Comment by shaunagm** [comment]
We're going to work on this one at the Sprints today.

**Comment by aawalker9** [comment]
Add warning to use HTTPS when cloning repository

**Comment by aawalker9** [comment]
Make sure to remind people to enter the hark directory before installing 
(econ-ark) C:\PythonPlus\64bit\pkgs\HARK>pip install -r requirements.txt

**Comment by aawalker9** [comment]
Unittest command does not contain '.' :
python -m unittest
