### ISSUE TITLE
Update installation instructions with additional instructions for GUI interface

### ISSUE THREAD

**Issue by LeJit** [econ-ark/HARK#268]
When following the "pip install" instructions on the HARK repo, I get an error when running HARK from the REPL. Since this library is installed in a new virtual environment, there are instructions about requiring a GUI environment to run the library.

**Comment by llorracc** [comment]
I think this is probably related to #199.  What environment is your REPL?

**Comment by adsk2050** [comment]
I was able to install econ-ark successfully in repl.it using the packages option located in left sidebar. You can try that meanwhile.

**Comment by llorracc** [comment]
Wow, repl.it looks pretty cool - I had not come across it before.  @MridulS, are you familiar with it?

**Comment by MridulS** [comment]
Indeed is looks promising. No need to install any python locally too.

**Comment by MridulS** [comment]
this has been fixed, https://github.com/econ-ark/HARK/pull/444
