### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by dclow** [econ-ark/HARK#3]
We need to figure out a better folder structure for the files.

I recommend something like having the files that actually have HARK in their name in the main folder.  ConsumptionSavingsModel.py can be in a folder called "ConsumptionSavingsModel", the DAP model can be in a folder called "DAPModel", etc.

**Comment by mnwhite** [comment]
Folder structure is now where it should be for beta release.  Files in /Testing need to be slightly edited to fix paths.
