### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#311]
There was a good presentation about documentation at the PASC19 conference.  [Here are the slides](https://pasc19.pasc-conference.org/program/schedule/presentation/?id=msa207&sess=sess155).

In particular I like the categorization of the documentation content into four kinds:

* Learning-Oriented (tutorials for people who want to learn the toolkit)
* Goal-Oriented: For people who want to accomplish a specific goal
* Information-Oriented: For people who want to find a specific piece of information

**Comment by shaunagm** [comment]
I've moved this over to the pre-existing [improve documentation](https://github.com/econ-ark/OverARK/issues/16#issuecomment-506770119) issue.
