### ISSUE TITLE
Integrate Zenodo, Zotero, and GitHub

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#312]
The last presentation at the PASC19 session on management of open source projects was by a person from the [The Research Software Directory](https://www.research-software.nl/) in the Netherlands.  They have a [blog](https://blog.esciencecenter.nl)

The software is available at [GitHub](https://docker.pkg.github.com/research-software-directory/research-software-directory)

He illustrated a technology for integrating Zenodo, Zotero, and GitHub.

In particular, whenever there is a new release, references to the software are updated in Zenodo and Zotero.

* GitHub-Zenodo integration to mint DOIs whenever there is a release.
* Research Software Directory has an Admin interface with **concept doi**
* Nightly scripts run to update references.

Again advocated using the cff file format: Google search looks for this and makes it easier to find your resources.

This is integrated with a "cite this software" web page.

**Comment by shaunagm** [comment]
Moved the content of this issue to a comment in the pre-existing [citation management issue](https://github.com/econ-ark/OverARK/issues/25#issuecomment-506768904).
