### ISSUE TITLE
What should the output of `simulate` be?

### ISSUE THREAD

**Issue by pkofod** [econ-ark/HARK#333]
I've been working a lot with `simulate` over these past weeks, and I've opened some issues as a result, and started a demark much like the solution demark. Here's another thing that has struck me as something that *could* be improved.

Currently, you specify
```
model = SomeModel(**paramdict)
model.solve()
model.T_sim = ...
model.track_vars = ['cNrmNow', 'mNrmNow']
model.initializeSim()
model.simulate()
```
and then you can grab `_hist` suffixed versions of `track_vars`.

I think it would make sense to gather the simulated variables (`mNrmNow_hist` and `cNrmNow_hist`) in a collection instead of just adding them to the "top-level" of the class. This could be a dictionary, but it could also be a `DataSet` class that had default methods for working with the data (convert to a panel data format with variables in columns and sorted by (id, t), calculate some moments, etc).

I have not made a prototype, I just wanted to mention it and start the discussion before it lost my attention.

**Comment by mnwhite** [comment]
Agree with this. We currently don't use any data-oriented packages in HARK,
but we can incorporate some basic features.

My intention when I set things up this way is that it's both impossible for
us (the developers) to predict what users will want to do with their
simulated data and that part of the code is "easy" for those users to
program for themselves (it's just playing with data). That is,
post-simulation stuff was intentionally left for users to craft bespokely
for their individual projects.

To the extent that there are simple convenience methods for making obvious
plots (like simple time series average), we should do that.

**Comment by pkofod** [comment]
One thing is data handling, the other thing is interfacing with the simulated data. Given your feedback, I have an idea for a simple improvement we can do.

**Comment by sbenthall** [comment]
@pkofod I'm interested in this functionality and wonder if you've gotten anywhere with the changes you were talking about on this issue.

**Comment by MridulS** [comment]
Possibly the solution to this will be when we figure out the way to integrate HARK with dolo.

**Comment by sbenthall** [comment]
This connects quite well to #837 
It would be natural for the history to be returned as a pandas dataframe.

**Comment by sbenthall** [comment]
Short term: return history object as is.

Longer term: design this w/r/t issue #837
