### ISSUE TITLE
ConsIndShockOpenCL code only works on specific configs

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#347]
ConsIndShockOpenCL is a rewrite of some of the models in ConsIndShockModel that should work on GPU's to allow for much faster solution and simulation.

It has been tested on a bunch of combinations of computer-OS-GPU and works on some and not on others (though the whole point of using OpenCL instead of CUDA was to be able to use it on almost any platform).  

On machines where generic OpenCL test suites work:

On MacOS 10.13.6 running on a late-2018 MacBookPro:
-- It works: 
      - Using the AMD Radeon GPU built into a 2018 MacBookPro
-- It fails (in different ways): 
      - Using the Intel GPU or the CPU 

On MacOS 10.13.6 running on a mid-2012 MacBookPro:
-- It fails: 
      - Using the Intel GPU or the CPU 
      - Using the Nvidia GPU

**Comment by llorracc** [comment]
At SciPy2019, I spoke to a number of people who are very up to date about the state of GPU computing, and reached the conclusion that further investment in OpenCL would be unwise, as it appears that the language has not gotten sufficient support to be a long-term viable alternative to CUDA.  I hope that changes, but at present the best option for someone wanting to write reasonably portable GPU code seems to be to use numba, which now has GPU support (which was not true when we originally wrote our OpenCL code).  While numba can interact either with Nvidia or with AMD GPUs, the code needs to choose one of the two platforms and use platform-specific protocols for that interaction.  Specifically, AMD has made available the rocm and rocr libraries which numba can interact with, so for now the only way to write "platform independent" code seems to be to write code that tests which platform it is running on and in the appropriate place executes the appropriately tailored code.

**Comment by michiboo** [comment]
Hi, is there any small issues that are related to this area? I am happy to have a go at it.

**Comment by MridulS** [comment]
CUDA yay!
