### ISSUE TITLE
"No solution" error is not reached in PerfForesightConsumerType for inf hum wealth

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#359]
Adding these two cells to the Gentle Introduction - Perfect Foresight notebook does not result in the warning message that the model has no nondegenerate solution, but instead gives the error messages below.

NewExample.PermGroFac = [1.05]
NewExample.solve()

/dhlib/lib/python3.7/site-packages/HARK/interpolation.py:774: RuntimeWarning: divide by zero encountered in true_divide
  alpha  = (x-self.x_list[i-1])/(self.x_list[i]-self.x_list[i-1])
/dhlib/lib/python3.7/site-packages/HARK/interpolation.py:777: RuntimeWarning: invalid value encountered in multiply
  y = (1.-alpha)*self.y_list[i-1] + alpha*self.y_list[i]

**Comment by JackShiqiLi** [comment]
I find that the method checkConditions were defined in the PerfForesightConsumerType but not called before SolveAgent() was called. I have Overwritten PreSolve() in PerfForesightConsumerType to allow for checkConsitions() to work in pull request #395 .

**Comment by sbenthall** [comment]
Has this been fixed?

**Comment by llorracc** [comment]
Yes.
