### ISSUE TITLE
A few weird variable names in TractableBufferStock

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#36]
The variable names in TractableBufferStock.py have been cleaned up as of 5/11/2016, but there are a few that still need fixing.  All of these seem to be temporary algebraic conveniences, and I don't know how to describe them in words off the top of my head:
- natural
- Beth
- Pi
- zeta

**Comment by pkofod** [comment]
This seems to have been fixed in #184, right?

**Comment by mnwhite** [comment]
I thought I closed this?

**Comment by pkofod** [comment]
No, I think you just closed the duplicate issue in #183
