### ISSUE TITLE
Journeys Into HARK

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#362]
@ericholscher @shaunagm,

Jan Rosa has been working with me to improve the HARK documentation, and I've had him look in particular for toolkits that do a good job of guiding new users into the substance of the toolkit, by constructing curated "journeys into HARK" for people with different backgrounds.  He's found some nice examples and what I would like to have him do is to create the rudiments of at least two different "journeys into HARK" -- one from the perspective of a first year PhD economics grad student, and one for someone with a lot of computer expertise but less economics grounding.  I'm sending this message because if the two of you have advice for him (esp about integration of such journeys into RTD), that would be useful to him.

**Comment by janrosa1** [comment]
I will be very grateful for your advice. Before, I added some auto documentation into RTD however, I have never integrated it with Jupyter notebook.

**Comment by ericholscher** [comment]
Great. All the integration with Sphinx is done via [nbsphinx](https://nbsphinx.readthedocs.io/) -- so that would be the best place to look for best practices. I haven't done much personally, but their docs are pretty good, and the maintainers are responsive.

**Comment by janrosa1** [comment]
Thank you! I will try this and start building the journeys!

**Comment by sbenthall** [comment]
@janrosa1 any updates on this?

I'm currently working on documentation aimed at those with more computer science experience, and less economics experience.

**Comment by janrosa1** [comment]
Hi,
I do not have any updates now - I sent the pull request in the late August
(all the notebooks integrate at my fork with nbshpinx). However if you
think that I should add something to the repositories, or have some
questions how I organized the "intro to HARK" for people with econ
experience (1st year PhD), please let me know. I will answer ASAP.
Best,
Jan

pon., 3 lut 2020 o 09:26 Sebastian Benthall <notifications@github.com>
napisał(a):

**Comment by MridulS** [comment]
implemented in https://github.com/econ-ark/HARK/pull/380
