### ISSUE TITLE
Widget for TractableBufferStockQuickDemo does not respond to R

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#368]
Though the sliders are working for all the other parameters, at the moment they are not working for R.

**Comment by MridulS** [comment]
Just checked in the DemARK https://github.com/econ-ark/DemARK/blob/master/notebooks/TractableBufferStock-Interactive.ipynb and R seems to work too in the widget.

**Comment by MridulS** [comment]
closing this, doesn't looks like an issue anymore.
R works fine by uncommenting `Rfree_widget` in `interact` in the notebook  https://github.com/econ-ark/DemARK/blob/master/notebooks/TractableBufferStock-Interactive.ipynb
