### ISSUE TITLE
Missing __init__.py in cstwMPC-RHetero/Calibration

### ISSUE THREAD

**Issue by bholtdwyer** [econ-ark/HARK#384]
There's no `__init__.py` in the Calibration folder of the heterogeneous agent model in the REMARK repository; as a result, you get an error like the following when you try to run do_min.py:

```
File "//acsnfs4.ucsd.edu/unix-home/econgrad/bdwyer/gsr_2019/REMARK/REMARKs/cstwMPC-RHetero/do_min.py", line 19, in <module>
    import Calibration.SetupParams as Params

ImportError: No module named Calibration.SetupParams
```

**Comment by llorracc** [comment]
@mridul could you quickly fix?

**Comment by mridul** [comment]
Hi
I think you tagged the wrong mridul

**Comment by llorracc** [comment]
@MridulS,

The other Mridul was right, I tagged the wrong one!
