### ISSUE TITLE
ConsPortfolioModel does not work with AdjustProb < 1

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#389]
@pkofod:

@MridulS and I spent the morning going over the ConsPortfolioModel and making sure it all worked.  We've made a [DemARK](https://github.com/econ-ark/DemARK) called ConsPortfolioModelDoc.ipynb mostly based on the demo file you had provided.

But we could not get one thing to work:  You had an example of the version that allows the probability of adjustment to be less than one, but it was calibrated with the probability equal to one.  When we tried to run it with AdjustProb < 1, it crashed with an error that looked like it was trying to evaluate utility at consumption of zero.  

Am guessing this will be an easy one for you to fix, but it wasn't so easy for Mridul and me to track down the problem, so I've assigned it to you.

**Comment by pkofod** [comment]
Great! But not so great with the bug. This definitely worked at some point, but there's a chance it broke in the last re-organization. Let me have a look.

**Comment by pkofod** [comment]
Yup, seems like I decided to change the construction of the inverse interpolant at some point, but had put AdjustPrb = 1.0 to verify that the solution was the same across formulations ( I had a very fine grid of discrete portfolio choices, and that step function should converge to the continuous solution). I'll post a PR in a few minutes
