### ISSUE TITLE
Error in README instructions

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#396]
Following through on the README instructions, after installation (using pip), and running in a Python 2.7.12 terminal, I run into an error on this line:

```
# Retrieve the solved value for human wealth normalized by permanent income 
PFexample.solution[0].hNm
```
I get the following error:
```
>>> PFexample.solution[0].hNm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ConsumerSolution' object has no attribute 'hNm'
```

I would expect this to not error out.

**Comment by llorracc** [comment]
Hmm, it's a typo -- should be hNrm, what exactly were you running when you got this?

**Comment by sbenthall** [comment]
I was following the instructions in the README.

https://github.com/econ-ark/HARK/blame/master/README.md#L133
