### ISSUE TITLE
Should time_flow be True by default in AgentType?

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#398]
I've been writing tests for core.py and in AgentType __init__ `time_flow` by default is set to False, i.e time is flowing in the reverse direction, is this a design choice? In the boarder scheme maybe it doesn't matter much as it's a superclass and while creating a child class `time_flow` can be overridden. But I guess when someone does `AgentType.timeFlip()` for the first time it should reverse time to backwards rather going from `False` to `True`. @llorracc @mnwhite thoughts?

A quick grep tells me that only `TractableConsumerType` and `BayerLuettickeAgent` have `time_flow=False` on initialising while other Agents/Consumers are in forward direction.

**Comment by mnwhite** [comment]
Yeah, you can change this.  It's irrelevant for TractableConsumerType,
because that type is *only* infinite horizon with a single period, so
there's nothing to reverse!

**Comment by MridulS** [comment]
Thanks for the quick response! :)
