### ISSUE TITLE
Markdown errors in HARKmanual causing Sphinx errors

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#420]
In issue #412, it's noted that with `recommonmark`, the `make html` Sphinx command errored.

https://github.com/econ-ark/HARK/issues/412#issuecomment-545105238

PR #411 "solved" this problem by removing `recommonmark`. Unfortunately, this appears to prevent Sphinx from parsing any markdown at all. The baby was thrown out with the bathwater.

I've isolated the broken markdown to these files:
https://github.com/econ-ark/HARK/blob/master/Documentation/HARKmanual/HARKmanual.md
https://github.com/econ-ark/HARK/blob/master/Documentation/HARKmanual/ContributingToHARK/ContributingToHARK.md

The former appears to be autogenerated from the original LaTeX version of the manual and contains many irregular looking image references, as they are are used for rendered mathematical formulae.

These documents have been generated for uses that are _not_ the sphinx-generated ReadTheDocs:
https://github.com/econ-ark/HARK/issues/409#issuecomment-546629439

Therefore, the errors they are caused are due to the confounded directory structure.
I'll remove these files as part of the documentation cleanup effort. See #409

**Comment by MridulS** [comment]
I was able to setup a readthedocs copy running at https://hark-mriduls.readthedocs.io <https://hark-mriduls.readthedocs.io/> with recommonmark and the HARKManual.
But I get the same recommonmark  error locally, this could be also about our local installations of the dependences.
