### ISSUE TITLE
Small (easy) improvements in LaborIntMarg model

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#427]
Two (tiny, not that important) tasks left to do after #392 was merged:

(1) To adjust the xlim and ylim for the infinite horizon figures so that they're "nice" like the lifecycle ones below.

(2) To add a little 6 line method that looks at some attribute of a LaborIntMargType, reading it as nth degree polynomial coefficients, and constructs self.LbrCost using that polynomial.  This is just so that time-varying LbrCost "comes from" somewhere as a constructed attribute, rather than being manually written in a parameter dictionary.

_Originally posted by @mnwhite in https://github.com/econ-ark/HARK/pull/392#issuecomment-548514666_

**Comment by mnwhite** [comment]
In fact, here's the code for that method, from a (private) branch:

`
    def updateLbrCost(self):
        '''
        Construct the age-varying cost of working LbrCost using the attribute LbrCostCoeffs.
        This attribute should be a 1D array of arbitrary length, representing polynomial
        coefficients (over t_cycle) for (log) LbrCost.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        None
        '''
        Coeffs = self.LbrCostCoeffs
        N = len(Coeffs)
        age_vec = np.arange(self.T_cycle)
        LbrCostBase = np.zeros(self.T_cycle)
        for n in range(N):
            LbrCostBase += Coeffs[n]*age_vec**n
        LbrCost = np.exp(LbrCostBase)
        time_orig = self.time_flow
        self.timeFwd()
        self.LbrCost = LbrCost
        self.addToTimeVary('LbrCost')
        if not time_orig:
            self.timeRev()
`

So no PhD in economics required, just the ability to copy-paste that code, remove 'LbrCost' from the class definition of time_vary, and call self.updateLbrCost() in from the update() method.

**Comment by llorracc** [comment]
Thx.  PhD-level econ is required for understanding what you are doing and why, but not for what to do.

**Comment by rkcah** [comment]
I will have a go at this. This is my first attempt at open source!

**Comment by mnwhite** [comment]
I already did #1, I think.

**Comment by rkcah** [comment]
I have successfully implemented the second feature.

I will send a PR then.

**Comment by MridulS** [comment]
fixed in https://github.com/econ-ark/HARK/pull/524
