### ISSUE TITLE
time.clock() deprecation warning

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#428]
time.clock() has apparently been deprecated, and the warning suggests using process_time() instead.  Any Linux user can do a fancy replace all to change every instance of clock -->process_time.

I don't think we use the word clock for anything in the code, so this is probably safe.

**Comment by MridulS** [comment]
time.clock() changed to time.time(), we don't use process_time as its py2 only https://github.com/econ-ark/HARK/pull/471
