### ISSUE TITLE
Euler error calculator

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#46]
ConsumptionSavingModel (and related models?) should have an Euler error calculator function to find the relative difference between consumption and optimal consumption.  The beginnings of this are sort of in a ConsumerType method, but I don't think it does anything at this time.

This has been on the back burner for a long time now, and we should get around to it soon.

**Comment by mnwhite** [comment]
Done for IndShock model, but not for other classes (they have placeholder methods that throw a not implemented error).  Has option to use current income distribution discretization or use an absurdly dense one.  Doing the latter reveals that our solution method is poor near the lower bound of m in some circumstances, for reasons that are too long to explain here.

Only works for one period infinite horizon models right now, must extend this.  Also should write something to "ignore" the Euler error when c_t is on the constrained portion; first order condition doesn't apply here, "Euler error" is meaningless.

**Comment by sbenthall** [comment]
The first order condition == the arbitrage equation in Dolo

The Euler error is the value of the right hand side of the equation (not set equal to 0).

**Comment by mnwhite** [comment]
This is part of the HARK 1 roadmap, in an automated way. Closing.
