### ISSUE TITLE
Show model equations for inspected HARK AgentType and Market classes

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#479]
For comparison, the `dolo.compiler.model.Model` class instances, when inspected in the REPL, provide some nice metadata and the equations for the model.

https://gist.github.com/sbenthall/54772209ab5108801a5fe166cff12b5b

Currently, with HARK AgentType and MarketClasses, it is difficult to find the equations of the models by inspecting the code or the objects.

The equations could potentially be put in the docstrings of these classes.
Or they could be printed to the user when the object is inspected. 

This may be related to #446 -- this could be a way to communicate the parameters used in the object definition in a structured way.

**Comment by sbenthall** [comment]
depends on #761

**Comment by sbenthall** [comment]
Related to #660 #612 

- If we refactor to have parameters grouped/ available , it will be possible to display them/

We don't have a SST on transition equations. The closest we'll get to that by 1.0 is FrameAgentType.

**Comment by sbenthall** [comment]
Moving to 1.1 now that this is resolved for parameters.
need frame/equations explicit for next stage

**Comment by sbenthall** [comment]
See #1085 
Will be feasible with #1427

**Comment by mnwhite** [comment]
Closing because this is a major part of the HARK 1 roadmap, and is actively being worked on.
