### ISSUE TITLE
PerfForesightConsumerType not in readthedocs

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#480]
In class today I was trying to show off hark.readthedocs.io as I was asking students to do the first hands-on exercise with the toolkit, which involved PerfForesightConsumerType.  So, I put PerfForesightConsumerType into the search box.  Pleasingly, it came back with a bunch of cases in which the type is used in DemARKs etc.

But what it did NOT come back with was any direct info on how or where PerfForesightConsumerType is implemented, or what its docstring is, or basically anything that was directly about the class.  

Is there something we need to do to make sphinx index the classes themselves?

**Comment by sbenthall** [comment]
Documentation for that class can be found here:
https://hark-sb.readthedocs.io/en/i468/api-cs-ConsIndShockModel.html#HARK.ConsumptionSaving.ConsIndShockModel.PerfForesightConsumerType

That will be in HARK master when this PR is pulled:
https://github.com/econ-ark/HARK/pull/469

I think that will be done at today's meeting, if not before.
