### ISSUE TITLE
Small: approxNormal

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#49]
Somehow HARKutilities has no function to construct an approximation to a normal distribution.  There are several known methods for doing this, and we really ought to have at least one in HARK.

**Comment by mnwhite** [comment]
This issue intentionally left unresolved for beta release at CEF; it's referenced in the user manual.

This is low hanging fruit-- an obvious and easy hole in HARK.  It would make a good test case for testing accepting contributions from "outsiders".  Hint hint.

**Comment by mnwhite** [comment]
Matlab code for Gauss-Hermite quadrature can be found at the link below.  This can be ported into Python (with attribution to Geert van Damme) quite easily.  We should add @memoize to the top of our function, and handle the trivial cases of n=0 and n=1.

https://www.mathworks.com/matlabcentral/fileexchange/26737-legendre-laguerre-and-hermite-gauss-quadrature?focused=5147547&tab=function

**Comment by ccutsail** [comment]
Hi! I'd like to try to tackle this if no one else has volunteered.

**Comment by mnwhite** [comment]
Please do.  It's quite easy and a good introduction to HARK.  As a heads up, it is fairly likely that the location of the file (within the archive) where you do this will change in the next week or two.  As you can see from the PR page, we are currently reworking the structure so that HARK is an installable package (with conda or pip).

All this really means is that you'll probably just have to copy-paste your function to a different file when you're done.  But please do this!
