### ISSUE TITLE
BUG: Gentle intro notebook fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by westurner** [econ-ark/HARK#513]
Run Gentro intro notebook on mybinder.org [1], click "Restart and Run All"

```Python
ModuleNotFoundError: no module named 'tqdm'
```

Adding ``#!pip install tqdm`` in a cell above does workaround the dependency issue. What depends on tqdm?

- https://github.com/econ-ark/HARK/blob/master/binder/requirements.txt
- https://github.com/econ-ark/HARK/blob/master/binder/postBuild
- https://github.com/econ-ark/HARK/blob/master/requirements.txt

[1] https://mybinder.org/v2/gh/econ-ark/HARK/master?filepath=examples%2FGentle-Intro%2FGentle-Intro-To-HARK.ipynb

**Comment by llorracc** [comment]
@westurner thanks for this!  

tqdm is just a little tool that makes a progress bar you can watch to keep track of how far a calculation has gone; we use it in cases where a calc takes long enough that a user might wonder if something has gone wrong.  Just added it recently (it replaced another, deprecated tool) and am surprised it did not get added to the "requirements.txt".  My best guess is that it is included in Anaconda3 and all our devs have Anaconda3 installed so it worked without our remembering to add it to the requirements.  @MridulS will fix.  We will have a new release later this week that should incorporate that fix.

**Comment by westurner** [comment]
Thanks!

**Comment by MridulS** [comment]
@westurner thanks for the report but this import statement shouldn't be there in the first place. tqdm/log_progress bar isn't used in the gentle intro notebook. I'll remove this.

**Comment by westurner** [comment]
Thanks
