### ISSUE TITLE
BayerLuetticke should be a REMARK

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#531]
@sbenthall and @MridulS, could you coordinate on turning BayerLuetticke into a REMARK?  And, @MridulS, we will want to be able to run both the OneAsset and the TwoAsset notebooks (or, really, their corresponding .py files) using your awesome Docker tool.

**Comment by sbenthall** [comment]
This issue duplicates #361.

**Comment by sbenthall** [comment]
Looking at the REMARK guidelines:

https://github.com/econ-ark/REMARK#remark-guidelines

It looks like the current BayerLuetticke code, which has 3 notebooks in it, would be an exceptional case to the REMARK standard, which has only one eponymous notebook.

How would you like the BL REMARK to be organized?

It would be easy enough to just copy the old code over, but I think if it's a true REMARK it may need to be structured differently.

**Comment by sbenthall** [comment]
History of BayerLuetticke (before getting moved to Examples):
https://github.com/econ-ark/HARK/commits/0.10.2/HARK/BayerLuetticke

**Comment by sbenthall** [comment]
Related to #570 ...

Is teh BayerLuetticke code written in a way that requires "backwards time"?

**Comment by llorracc** [comment]
No.

**Comment by llorracc** [comment]
For my last class in Oslo today, I decided to copy BayerLuetticke wholesale to the REMARK repo.  I've made some small edits to it there, and from now on that should be considered the "master" version.

I agree that for it to be a proper REMARK it would need a bit of restructuring.  In particular, it would need a `do_all_code.sh` script in the root directory.  Will try to get to that.

**Comment by sbenthall** [comment]
Oh, I just saw this comment.
If https://github.com/econ-ark/REMARK/tree/master/REMARKs/BayerLuetticke is not the canonical version of this, the the example/ version can be removed.

I'll do that in a PR
