### ISSUE TITLE
AIC condition is not checked on IndShockConsumerType

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#534]
As of this PR merge:
https://github.com/econ-ark/HARK/pull/530

the `IndShockConsumerType.checkConditions()` method no longer calls its superclass's `checkConditiosn()` method.

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsIndShockModel.py#L2273

The `IndShockConsumerType.checkConditions()` method does not test and set the `AIC` condition variable, though this is referenced in the method documentation. This is either an error in the documentation, or an error in the code.

This change was caught by the tests in PR #526. As there is a question of method scope here, I'm not sure whether to adjust the tests or mark the change in functionality as a bug.

**Comment by mnwhite** [comment]
This is definitely a mistake, good catch.  The AIC applies to
IndShockConsumerType and should be evaluated by checkConditions (or inherit
from PerfForesight).

**Comment by llorracc** [comment]
I'm a little confused about how inheritance works here.  The AIC and AIF are identical in PerfForesightCRRA and ConsIndShockModel (as well as for KinkedRconsumerType), though some of the other conditions are not.  Is the right way to prevent the calculation from being done twice (or three, or n times, where n is the number of models that inherit from PerfForesightCRRA), to somehow invoke PerfForesightCRRA.checkConditions (presumably in some "quiet" mode where it can't say anything) and inherit the values from there?  Or, what is the right way to do this to avoid copy-and-pasting the same code (and thus introducing opportunities for error) many times?

**Comment by sbenthall** [comment]
I would be very happy to take on this issue and work on a PR in order to model how inheritance might be used elegantly in this case.

**Comment by mnwhite** [comment]
Essentially, yes.  The first thing that ConsIndShockModel.checkCondtions
should do is `PerfForesightConsumerType.checkConditions(self)`.  I believe
that used to be in the old version.  That will run the method from its
parent class on itself, which includes calculating the AIC.  A subclass
inherits all of the parent class' methods, but if you re-define that method
in the subclass, it completely wipes out the inherited definition; you have
to explicitly say "do the parent class stuff, then this other stuff".  We
do this with the update method a lot.

**Comment by llorracc** [comment]
OK, that makes sense.  

Seb is going to think about this.  One idea Seb proposed was that we make the various tests standalone methods.  Like, there would be an AIC and RIC method which could be inherited unchanged by ConsIndShockModel, and then checkConditions could just invoke the appropriate tests in order.  That sounds like a good way to refactor this to avoid replication of code.

**Comment by sbenthall** [comment]
The refactoring Chris asked for has been merged with #536 

I would like to come back to this and do some more refactoring later.
But I don't want to touch this more without input from Chris, because I know this feature is key to the next release, which is tied to a particular publication.

I think next steps on working on this checkCondition code would be to write automated tests for the conditions, both succeeding and failing cases. See #504
