### ISSUE TITLE
"quick fix" error in estimationparameters in SolvingMicroDSOPs

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#551]
There was an error while importing estimationparameters from SolvingMicroDSOPs but it seems to not exist anymore. By removing the fix https://github.com/econ-ark/HARK/blob/master/HARK/SolvingMicroDSOPs/Calibration/EstimationParameters.py#L11 (making it true) doesn't seem to produce any error now. Checked against all demarks and SolvingMicroDSOPs REMARK.

I'm not sure where/how this bug was solved.

**Comment by llorracc** [comment]
Great.  Are you saying you've merged in the fix?  Or do you still need to make a PR?

**Comment by MridulS** [comment]
Still need to send in the PR, just wanted to check in if someone knows how/where it was fixed.
