### ISSUE TITLE
Some LaTeX math does not translate properly into sphinx in ReadTheDocs

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#555]
For example, in the table

https://hark.readthedocs.io/en/latest/example_notebooks/GenIncProcessModel.html#Example-parameter-values-to-solve-GenIncProcess-model

for some reason the second line is $:nbsphinx-math:`rho `$ rather than simply the greek letter, and several similar examples.  

Went back and looked at the original document and in this case and several others, the problem seems to be that nbsphinx treats spaces as part of the name of an object, and the object was defined as $\rho $ rather than $\rho$ (space between the o and the $).  So, we'll just have to be careful about that.

**Comment by sbenthall** [comment]
More examples of this: 

First line here. 
https://hark.readthedocs.io/en/latest/example_notebooks/Gentle-Intro-To-HARK.html#Your-First-HARK-Model:-Perfect-Foresight

Note in the notebook, there is a line 

`$$\newcommand{\CRRA}{\rho}\newcommand{\DiscFac}{\beta}$$`

before the text.

Also, this table:
https://hark.readthedocs.io/en/latest/example_notebooks/KinkedRconsumerType.html#Example-parameter-values-to-construct-an-instance-of-KinkedRconsumerType

**Comment by sbenthall** [comment]
I've tried some fixes here for the problem you raise and some other ones that have come up.

I have to say that this is quite difficult to resolve thoroughly.

I'm finding that LaTeX interpreters vary across:
 - Jupyter notebook
 - Jupyter lab
 - My local sphinx documentation build
 - ... possibly the RTD documentation engine?

The result is that this feels like whack-a-mole; trying to 'fix' things in one area brings up problems in another.

I wonder if there's a better strategy for approaching this than I've been using.

**Comment by llorracc** [comment]
It's even worse than you describe.  Even INSIDE a jupyter notebook, what works and what doesn't is different in different contexts:

1. In Markdown cells
1. In matplotlib
1. Depending on whether or not you have the `latex_envs` notebook extension active
1. Depending what (if anything) the contents of the local `latexdefs.tex` file might be

I've just posted a PR that I hope will fix some of the problems on the Gentle notebook; we'll see when Sphinx recompiles.

Particularly frustrating to me is that I can't figure out when the amsmath `\underline` command will work.  Sometimes it works and sometimes it doesn't.  A bit of research informs me that the jupyter notebook environment uses MathJax to render latex math.  In order to get underline to work, you need to have MathJax load the AMSmath.js extension.  But I can't figure out when that extension gets loaded and when it doesn't.  

I'm pretty sure there's nothing we can do except go for the lowest common denominator: Restrict ourselves to whatever components of latex work in all contexts.  But that's too restrictive; in particular, I really need my underlines!  (There's a workaround that I have added to the Gentle notebook, which is that you can do `\underset{\bar{}}{[character]}` but this only works if you need to underline a single-character object, and the bar is much smaller than the underline (much smaller than you would like).

**Comment by sbenthall** [comment]
Another bug:

`\LiveFac` in this: https://hark.readthedocs.io/en/latest/example_notebooks/Gentle-Intro-To-HARK.html#Your-First-HARK-Model:-Perfect-Foresight

**Comment by sbenthall** [comment]
CCRA in this table:
https://hark.readthedocs.io/en/latest/example_notebooks/PerfForesightConsumerType.html#Example-parameter-values-to-construct-an-instance-of-PerfForesightConsumerType

**Comment by sbenthall** [comment]
Several entries in this table:
https://hark.readthedocs.io/en/latest/example_notebooks/KinkedRconsumerType.html#Example-parameter-values-to-construct-an-instance-of-KinkedRconsumerType

**Comment by sbenthall** [comment]
These are all the remaining math errors I could find in RTD. I'll whack these moles!

**Comment by sbenthall** [comment]
It looks like all of these problems arise when trying to use a `\newcommand` in notebook, then rendering it with sphinx.

The fix appears to be to replace these commands with the target symbol.

**Comment by sbenthall** [comment]
Ah, there are also extra spaces as in the original issue.
