### ISSUE TITLE
run_remark() should convert any ipynb files to py files if no py files exist

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#559]
The users of the REMARKs are likely to be very unfamiliar with python, Jupyter notebooks, etc.  

Right now, if there is no .py file present in a directory, the user is instructed to 'make sure jupytext synced file of the notebook is available in the Code/Python directory' which may seem like gibberish to a newbie.

It would be better just to run nbconvert on whatever ipynb files might be in the directory, print a message indicating that you are 'Converting Jupyter notebook(s) to plain python files' and then proceed as if nothing had happened.

**Comment by MridulS** [comment]
update the run_remark script in https://github.com/llorracc/BufferStockTheory-Latest/commit/8744746e2344e6aa8e1bc17321decb39104095df
