### ISSUE TITLE
Bellman form equations for the "cyclical" example

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#563]
(Related to #562)

There is a "cyclical" example at the end of this example notebook:
https://github.com/econ-ark/HARK/blob/master/examples/ConsIndShockModel/IndShockConsumerType.ipynb

It demonstrates the functionality of HARK that it can model a situation with cyclically changing parameter values.

I cannot find a Bellman form representation of this model.

**Comment by sbenthall** [comment]
Am I correct in thinking that what HARK is doing for cyclical models is essentially:
 - Introducing a new state variable *c* and new parameter *C*
 - update rule: _c' = c +1 mod C_
 - allowing parameters to be vectors of length _C_, in which case other update rules will refer to the scalar value of that vector indexed at _c_

**Comment by mnwhite** [comment]
Sort of?  But time-varying parameters are "lists of length C" anyway,
regardless of whether the model is cyclical.

**Comment by sbenthall** [comment]
I'm trying to pin down the math.

My understanding is that there are four cases:
 - A) infinite horizon, non-cyclical ("simple")
 - B) finite horizon, non-cyclical ("lifecycle", maybe confusingly.)
 - C) infinite horizon, cyclical ("seasonal")
 - D) finite horizon, cyclical (???)

I am under the impression that in (A), all parameters are time-invariant and scalars.

I am under the impression that in (C), there may be time-varying parameters that are vectors of length _C_, indexed by _c_.

I think what you are saying is that in (B), there can be time-varying parameters. These would be vectors of length...I guess it's of length _L_, the lifespan of the agent.

I would expect that in case (D), you might have time-varying parameters of either length C or length L, depending on whether they were seasonal or age-dependent variables.

Am I getting warmer?

**Comment by mnwhite** [comment]
Whether a particular parameter is in time_vary or time_inv does not depend
on whether it's finite or infinite horizon, or on whether the number of
periods in the cycle is 1 or greater than 1.  It's not particularly
*meaningful* to speak of "time-varying" parameters when the same period is
repeated over and over again, but it's there.

When you make an instance of an AgentType subclass, you would put the same
data type into an attribute no matter what.

In case B, each attribute named in time_vary should be a list of length
T_cycle.  But that's true *in A, C, and D* as well.

**Comment by sbenthall** [comment]
Ok. I think I understand.

All model variables named in `time_vary` are "seasonal" variables. They vary over cyclic time.

I think what i just realized is that HARK does not really support the representation of what I've called case B. I.e, there's no native notion of an age-varying variable.

Rather, if I understand correctly, the way HARK currently handles a lifespan is like case (D): a finite horizon model, with `L = C`. `L` being the length of the horizon, `C` being the length of the cycle.

Ergo, variables like `DiscFac_timevary` here:
https://github.com/econ-ark/HARK/blob/master/examples/LifecycleModel/EstimationParameters.py#L41-L64

**Comment by mnwhite** [comment]
No, case B is completely normal.  You just set cycles=1, and then have the
attributes named in time_vary be lists of length T_cycle.  That's it.
That's a direct representation of the lifecycle.  The "cycle" of periods
happens only once in a standard lifecycle model.

You don't even need to go into the SolvingMicroDSOPs example, which treats
DiscFac as age-varying (which is non-standard).  LivPrb is in time_vary in
the basic IndShockConsumerType and PerfForesightConsumerType.

**Comment by sbenthall** [comment]
I'm afraid I'm having difficulty mapping between Bellman equations and the way HARK represents models.

I think `T_cycle` maps to the variable `C`, in the schematic math I've been using in this issue.

Where would you put `cycles` into a Bellman equation?
