### ISSUE TITLE
Readme.txt examples out of date

### ISSUE THREAD

**Issue by ganong123** [econ-ark/HARK#57]
From the readme: 
```
6) Test one of HARK's sample modules with one of the following commands:

"run ConsumerExamples"
"run SolvingMicroDSOPs"
"run cstwMPC"
"run TBSexamples"
```

The examples in instruction 6 of readme.txt are out-of-date. 
(1) It seems that ConsumerExamples has become ConsumptionSavingModel.
(2) All the examples are now in subdirectories

(this is my first issue post and it is incredibly pedantic. I will post more substantive stuff as I find it, but I figured that you'd rather know about bugs, particularly those that affect people just starting out.)

**Comment by mnwhite** [comment]
See issue #3, about README.txt being updated right before CEF.  As it so happens, I began doing so about 10 minutes ago.  Also, welcome to HARK!

**Comment by mnwhite** [comment]
Sorry, issue #13.

**Comment by ganong123** [comment]
Ha! I just started reading through the old issues and found that one.
