### ISSUE TITLE
Simulator: hand in rules one at a time or all together?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#571]
@llorracc writes:

> An important question to think about as we move in that direction is whether the right approach is to have a simulator that just simulates one period at a time and we expect the user to feed it a sequence of rules one by one, in which case it is up to the user to feed the simulator the rules in the right order, or whether we want to be able to feed the simulator an entire sequence of decision rules and have it do all of them together and then return a result. If there were no considerations of efficiency, I'd vote for the former approach, but it could be that such an approach would be highly inefficient and slow because there would be so many objects being passed back and forth between the one-step simulator and the code that was using it to produce a sequence of periods.

**Comment by sbenthall** [comment]
I'm a little lost on this one.
@llorracc could you explain what you meant here? Otherwise, I'll close the ticket.

**Comment by llorracc** [comment]
Like, in the portfolio model.
| Step | Rule | Description | State-In | State-Out | 
| --- | --- | --- | --- | --- |
| `c` | `cFunc` | `consumption function ` | m $\mathbb{R}_{+}$ |

**Comment by sbenthall** [comment]
I think (2) can be (1) considered at a different level of abstraction.

**Comment by mnwhite** [comment]
Closing as stale, and never really understood as an issue. I agree with Seb that this is just a matter of abstraction. Efficiency-wise, passing objects in Python isn't costly because it's a memory pointer. Doing so in Matlab (e.g.) is very costly because a new copy is created in memory.
