### ISSUE TITLE
checkRestrictions() ... related to checkConditions?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#574]
There is an empty method in the core Agent class, `checkRestrictions`, which seems to be there to impose or test constraints on the model parameters:

https://github.com/econ-ark/HARK/blob/b1b14ad1539495e11d483f54bedf5f569d3885ce/HARK/core.py#L411

It's only used in one place in the HARK library, in the PerfForesightConsumerType:

https://github.com/econ-ark/HARK/blob/3d3dbfea9f2192213ece38ca6912ed249336e392/HARK/ConsumptionSaving/ConsIndShockModel.py#L1655

My impression is that `checkRestrictions` may be intended to do work similar to `checkConditions`, and that the two methods could be merged into one.

Does that sound right?

**Comment by sbenthall** [comment]
Maybe a difference between `checkRestrictions` and `checkConditions` is that the former raises an Exception, whereas the latter currently prints warnings.

`checkRestrictions` is not called from anywhere in the code, however, so the test has to be done manually and the Exception is not going to stop anything from running.

**Comment by sbenthall** [comment]
I was mistaken--there is a call to checkRestrictions() in preSolve()

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L430

This makes it look like the intent of checkRestrictions is very much what's intended by checkConditions. See #283 

@llorracc is it possible that this functionality needs to be merged together?

**Comment by llorracc** [comment]
From what @mnwhite just said (elsewhere), it sounds like checkRestrictions is more about making sure various ingredients are of the right type (e.g., lists, etc).  The code won't work, probably, if they are the wrong type.  checkConditions is more about informing the user about various theoretical characteristics of the model that can be proven to hold true under various configurations of parameter values (like 'a target asset ratio exists').  

However, the names of the two methods are sufficiently similar that there is the potential for them to be confused with each other.  Perhaps we should change one of the names.

**Comment by mnwhite** [comment]
Hmm, it looks like what I thought was in checkRestrictions is actually not;
I was thinking of checkMarkovInputs in MarkovConsumerType.  Is this method
actually meaningfully defined anywhere?

**Comment by sbenthall** [comment]
The one place that it is not an empty method, it:
 - tests for whether DiscFac < 0
 - if so, it fires an Exception

https://github.com/econ-ark/HARK/blob/3d3dbfea9f2192213ece38ca6912ed249336e392/HARK/ConsumptionSaving/ConsIndShockModel.py#L1659

It looks like it was written by @pkofod about 9 months ago.

**Comment by sbenthall** [comment]
For 0.10.9 release!

**Comment by sbenthall** [comment]
Taking another look at this...

This seems connected to the ambiguity around what preSolve is supposed to be doing. See #576 

These should be handled together.

As we get more clarity into how model parameters are being set, we may want to allow users to stipulate restrictions on other parameters as well.

These would need to be written as equations or functions, not hard-coded.

Punting this to 1.1

**Comment by llorracc** [comment]
OK.  A case could be made for "restrictions" being circumstances under which the user has fed the code parameter values for which there is guaranteed to be no sensible solution, while "conditions" would be circumstances under which there is (or might be) a solution, but we know something interesting about it.  On the whole, I think it is probably better just to leave everything in checkConditions, but could perhaps be persuaded to change my mind.

**Comment by sbenthall** [comment]
"checkConditions" -- conditions for what?
"checkRestrictions" -- restrictions for what?

I think it would be best to be precise about the functional or theoretical implications of these conditions, and organize them that way.

**Comment by mnwhite** [comment]
I'm closing this because both of these methods have been significantly changed since this issue was last discussed. I've tagged it as 1.0 because *parameter restrictions* are being incorporated as part of that roadmap. I believe the Parameters class also already supports this.
