### ISSUE TITLE
exec() use in makeShockHistory and simulate() can be improved

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#575]
A core piece of `makeShockHistory()` dynamically writes Python code and executes it with `exec`:
https://github.com/econ-ark/HARK/blob/b1b14ad1539495e11d483f54bedf5f569d3885ce/HARK/core.py#L547

There's a core line in `simulate()` that does this as well.
https://github.com/econ-ark/HARK/blob/b1b14ad1539495e11d483f54bedf5f569d3885ce/HARK/core.py#L735

And also here, the method that clears the history variables:
https://github.com/econ-ark/HARK/blob/b1b14ad1539495e11d483f54bedf5f569d3885ce/HARK/core.py#L741

It appears that this is done because of a particular naming convention: the fields storing the history of the shock and tracked variables are names {variable name}_hist. `exec` is being used for the variable assignment of these dynamically constructed variable names.

For various reasons, `exec` is considered a 'bad code smell`--if you're using it, it probably means you are doing something wrong. References:
 - https://rules.sonarsource.com/python/RSPEC-2317
 - https://lucumr.pocoo.org/2011/2/1/exec-in-python/

A different way to organize these variables would be to give them a namespace.
Rather than call them '{variable_name}_hist, you could put them into a dictionary field, `hist[variable_name]`. Then it would be a lot easy to store the history without the weird `exec` statement.

This would also make it easier to find all the history variables in a generic way. I would argue that this is a more extensible and navigable design.

**Comment by mnwhite** [comment]
We can also just use getattr and setattr.  I wrote those lines before I
knew they existed, and never fixed it.

**Comment by sbenthall** [comment]
Cool, I'll add this to the 1.0 work pile.

What I've been calling 'namespacing' is very similar to what @pkofod has proposed in #333 
I see these as very connected issues.

There's a brief discussion on this PR about the potential use of Pandas in HARK:
https://github.com/econ-ark/HARK/pull/570#issuecomment-599242375

A Pandas dataframe is a nice representation of a "table" of data: named columns, indexed rows, a value for each cell. It's much like a spreadsheet or a relational database, has very good performance (because of the underlying C implementation), and has a lot of helpful functionality built into the data structure (such as ability to export to CSV and other formats).
