### ISSUE TITLE
Bayer-Luetticke is still python2.7 oriented

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#583]
Also, per the last comment in issue #361, it needs to be moved to be a REMARK

**Comment by sbenthall** [comment]
#531

**Comment by sbenthall** [comment]
@llorracc Can you elaborate on what you mean by this?

The notebooks are executing fine for me in a Python 3 environment.

Maybe you are referring to the `in_ipynb()` and notebook `matplotlib` magic command handling, which I believe can now be safely removed?
