### ISSUE TITLE
Lifecycle example still depends on HARK/SolvingMicroDSOPs...

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#584]
The LIfecycle example still depends on HARK/SolvingMicroDSOPs... for a parameters file.

**Comment by mnwhite** [comment]
The lifecycle parameters in the SolvingMicroDSOPs parameter file should be
moved into ConsIndShockModel.py as another example dictionary.  It should
probably overwrite the current init_lifecycle, which just has made up
parameters to show how to do finite horizon.
