### ISSUE TITLE
Deprecating use of latex_envs and associated latexdefs.tex

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#599]
It has long been an ambition of the project to have concordance between LaTeX names of commonly used objects in our Jupyter notebooks, and the corresponding python variable names.  For example, LaTeX \DiscFac and python `DiscFac` should be the same thing.  One way of accomplishing this within Markdown cells is to require the notebook extension `latex_envs` which:

1. Gives Markdown the ability to correctly interpret some very useful standard LaTeX environments (like `eqnarray`)
1. Reads in the contents of a file named `latexdefs.tex` in the notebook's directory
    * The latexdefs.tex file used in various places contains a subset of the variable name conventions (like `DiscFac` defined in the NARK (Notation for the ARK) 

This arrangement is problematic, however, for several reasons:
1. It does not work if someone looks at the notebook without having the `latex_envs` nbextension installed
1. If the notebook is moved to a different directory but the `latexdefs.tex` file is not moved, the notebook no longer renders properly for reasons that will not be obvious to a user.

I propose that @MridulS investigate whether it is possible to incorporate this functionality in a tool that we put into econ-ark-tools, which would always be invoked in every Jupyter notebook we create.  Basically, the idea would be to import the `latex_envs` notebook extension and import the contents of a canonical version of the `latex_defs.tex` file that we would put in `econ-ark-tools`.

That would solve both problems, I think.

**Comment by sbenthall** [comment]
>  For example, LaTeX \DiscFac and python DiscFac should be the same thing.

In python, `DiscFac` is currently a symbol, or a string.
It has no value except what is assigned to it; in most cases it is a key in a dictionary, which later becomes an attribute name on a Model class.

I think what you are proposing is that mathematical values in HARK should be a richer kind of object, one that has a LaTeX representation that can be worked with programmatically (for example, to auto-generate notation tables in notebooks).

**Comment by llorracc** [comment]
Hmmm, that's an interesting idea, and one that is worth thinking about.  But, actually, all I meant was that since we need to have a symbol or string to represent this mathematical object (and many others) both in LaTeX and in python, it will make the relationship between the LaTeX code in our notebooks and the python code in our toolkit easier to digest if as much as possible we use the same symbol or string in both places.  That is, rather than calling it `\beta` in LaTeX and `DiscFac` in python, we call it `\DiscFac` in LaTeX and `DiscFac` in python which makes the mapping between LaTeX math (which you see when you double-click the markdown) and python code easier to see.  It would be great if Mridul can figure out how to build this into a default tool in `econ-ark-tools.`

**Comment by MridulS** [comment]
I need to look more into it, but top of my head if there is a consensus of the greek notation we can use the unicode representation of them in the jupyter notebooks as well as our code and thus in the latex notebooks.
Maybe we would need a mapping between unicode and latex. (Someone would have already looked into this)

Example:

β = 10

Is a totally valid python expression in python3.

**Comment by llorracc** [comment]
Unfortunately, there are only a few Greek letters for which there is a consensus of that kind.  I'd say that maybe 80 percent of papers use \beta for the discount factor, but some use \delta and others use other letters.  Plus, there's no standardized way to type the unicode characters; different editors require different key sequences to get any particular unicode result, so I've found it hard to train my fingers to type the Greek characters.  Whereas typing DiscFac is the same on all keyboards.
