### ISSUE TITLE
Equivalency between 2 models/agents. 

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#612]
Should HARK have the `__eq__` method to compare 2 HARK objects?

For example

```
example_1 = PerfForesightConsumerType(**PF_params)
example_2 = PerfForesightConsumerType(**PF_params)
```

`example_1 == example_2` should be True (it will give it False) but currently HARK doesn't have the ability to test this.

**Comment by sbenthall** [comment]
That sounds nice.

A couple thoughts:
 - The `distanceMetric` functionality seems to do some of this. That functionality is old code. It could probably be reimplemented in a more pythonic way. Maybe that would be connected to this issue.
 - Would an unsolved and a solved AgentType be equivalent? What if a simulation had been ran, with different parameters? The meaning of 'equivalence' might be more intuitive if some of the functionalities currently handled in AgentType were disentangled, see #495

**Comment by MridulS** [comment]
> Would an unsolved and a solved AgentType be equivalent? What if a simulation had been ran, with different parameters? The meaning of 'equivalence' might be more intuitive if some of the functionalities currently handled in AgentType were disentangled, see #495

Different parameters should mean the agent are not equivalent. There isn't any way to get all the parameters of an agent right? something like `AgentType.parameters`

**Comment by mnwhite** [comment]
distanceMetric is used for comparing solutions, to see if it has converged
on successive iterations.  I'm not sure there's a use case for comparing
instances of AgentType subclasses for equality.

**Comment by sbenthall** [comment]
> There isn't any way to get all the parameters of an agent right? something like `AgentType.parameters`

I don't believe there is.
But this is high on my refactoring wishlist.

It's a little complicated to do this... see #492

**Comment by sbenthall** [comment]
#760 #761 are related

**Comment by sbenthall** [comment]
See also #660

**Comment by sbenthall** [comment]
> distanceMetric is used for comparing solutions, to see if it has converged on successive iterations. I'm not sure there's a use case for comparing instances of AgentType subclasses for equality.

This makes sense to me.

I have wondered for a while why AgentType inherits from HARKObject, since there is no use case for using its distanceMetric function.

I think what it's using currently is `assignParameters`.

Does `assignParameters` ever get used on a solution object? If not, then I think it would be safe to split HARKObject into two classes.

It would be safe to do that anyway, since the two classes can be combined with multiple inheritance when necessary.
