### ISSUE TITLE
single expected value computation method

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#621]
@mnwhite mentioned today that the expected values of discrete distributions are computed in many places throughout the HARK code, and that with the new DiscreteDistribution class this could be implemented more cleanly once as a class method.

Matt, if you could point me to an example place in the code where that's being done, I can work on making these changes.

**Comment by llorracc** [comment]
On this subject, our ideal endpoint would be something like what Mathematica does:

Expectation[z, z \[Distributed] NormalDistribution[\[Mu], \[Sigma]]]

yields $\mu$

while 

Expectation[z, z \[Distributed] NormalDistribution[0.5,1]]

yields 0.5

Expectation[(z-\[Mu])^{2}, z \[Distributed] NormalDistribution[0.5,1]]

yields 1.

It will be a long time (if ever) before we can do the former (that is, leave the objects in symbolic form).  

What we could do fairly quickly, I think, is to test whether the distribution z is a discrete distribution with a list of probabilities and values, and everything is numerical, and we could return what we do now.  

Again, I wonder whether than SymPy has infrastructure for this already?
