### ISSUE TITLE
DiscreteDistribution point masses to be a private attribute

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#623]
`X` is not a good attribute name.

Better to use something more reflective of the mathematical term

**Comment by sbenthall** [comment]
Notes from today's meeting:

The idea is to have flexibility for a multivariate distribution where the variables are not independent.
This is used elsewhere in HARK.

Ideally, there should be a multivariate distribution object from which it is possible to extract the marginal distributions, with various options for methods of discretization and approximation.

**Comment by sbenthall** [comment]
#730

**Comment by sbenthall** [comment]
Reopening this. Dolo IID Process integration is for a later milestone now #611 
This can be solved easily by the 1.0 release, and is implicated directly in the now manageable solution code simplications #625

**Comment by sbenthall** [comment]
This issue is awkwardly named; I see now that this simple "name change" implicates several other issues, including #120  and #625.

It may require further review to determine the right short term solution.

One may be: through `calcExpectations` (#625), there should be no reason for the point masses to be a _public_ variable.

**Comment by llorracc** [comment]
The way to think about this is to think about the discretized distributions generically as approximations to idealized continuous distributions.  So, for example, we might want to say that the setup is one in which the "truth" is that the permanent shocks to idiosyncratic permanent income and to aggregate stock returns are jointly lognormally distributed with a covariance coefficient of 0.1.  But in practice any numerical solution will have to approximate that with some particular discretization of the relationship, which is a matrix.  Among competing discretizations, we want to have an unambiguous standard of "which one is closer to being right" -- in case the models differ in some important prediction.  We want the unambiguous answer to be "whichever one is closer to the answer you get as you increase the fidelity of the discrete approximation to the continuous assumption."  A 1000x1000 approximation is going to give a closer approximation than a 3x3 approximation.  So whichever discretization gives an answer closer to the more accurate approximation is right.  

So, it is not worthwhile to devote any effort to trying to efficiently meld the unemployment shock with the transitory shock.  The interesting questions will all have to do with either (a) correlations between the transitory and permanent shocks; or (b) correlations between the unemployment shock and either transitory or permanent shocks (conditional on not becoming unemployed).  

PS.  I'd really, really like to get into HARK 1.0 the default of our distributions being ones with point masses at the min and max values of some standard deviation, per the discussion elsewhere.  Matt and I strongly agree on this subject, for deep and powerful reasons.  We both wish I'd done it a long time ago (like, 20 years ago).  It's clearly the right way to do things.

**Comment by sbenthall** [comment]
> PS. I'd really, really like to get into HARK 1.0 the default of our distributions being ones with point masses at the min and max values of some standard deviation, per the discussion elsewhere. Matt and I strongly agree on this subject, for deep and powerful reasons. We both wish I'd done it a long time ago (like, 20 years ago). It's clearly the right way to do things.

Is there an existing issue for this? If not, could you make one describing what you mean?

**Comment by sbenthall** [comment]
> The way to think about this is to think about the discretized distributions generically as approximations to idealized continuous distributions.

I suppose this will be fixed as part of #640 then.

Looks like this ticket can be closed as its scope is covered in better detail in other issues.
