### ISSUE TITLE
test case and updates for non-independent returns ConsPortfolioModel case

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#638]
ConsPortfolioModel can be ran with a non-independent return distribution.

The code for this case has not yet been refactored to take into account DiscreteDistribution.

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsPortfolioModel.py#L707-L712

This case is probably missing from the automated test suite.
This issue is for making the test and correcting this code.

**Comment by llorracc** [comment]
For future reference of anyone who takes on this task, let me point you to some lecture notes and a corresponding Mathematica notebook that shows how to construct equiprobable distributions that allow for correlations between two independent variables.  It shouldn't be that hard to translate the Mathematica code into python.

http://www.econ2.jhu.edu/people/ccarroll/public/lecturenotes/AssetPricing/Portfolio-Multi-CRRA/

**Comment by sbenthall** [comment]
@Mv77 since you are working with the Portfolio model closely, maybe you are the best person to take a look at this.
Is there any way the Distribution classes could be expanded to make this sort of operation easier?

**Comment by sbenthall** [comment]
For reference, the `combineIndepDstn` function:
https://github.com/econ-ark/HARK/blob/master/HARK/distribution.py#L906

For this issue, there needs to be an implementation of a more sophisticated way to discretize correlated normal distributions....

**Comment by sbenthall** [comment]
See #120

**Comment by sbenthall** [comment]
See also https://github.com/econ-ark/HARK/issues/1106#issuecomment-1025908532

**Comment by Mv77** [comment]
The easiest way to do this with current tools would be to add a "crash" state where income shocks and risky return draws would be very low. The crash state can happen with some probability `p`, and otherwise  shocks are drawn from their usual distributions.

I might take a look after I am done with the newborn shocks issue.

**Comment by mnwhite** [comment]
The current ConsPortfolioModel handles arbitrary shock distributions using DiscreteDistribution, including correlation between income and returns. Closing.
