### ISSUE TITLE
Lorenz share code (bring in from cstwMPC)

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#667]
cstwMPC REMARK has Lorenz Share code.
This should be generalized and included in HARK

**Comment by mnwhite** [comment]
It already is.  It's getLorenzShares in HARK.utilities (or maybe another
module).

**Comment by sbenthall** [comment]
Ah, ok. The motivation for this is getting the Uncertainty and the Saving Rate DemARK to work now that the cstwMPC code is removed.

It depends on a cstwMPC version of the Lorenz curve code. 

But maybe that is a legacy dependency and it can be replaced with what's in HARK

**Comment by llorracc** [comment]
Now that we have the SCF data in HARK.datasets, it should be straightforward to figure out how to redo things so that the DemARK simply uses the built-in HARK Lorenz curve tool on the built-in SCF data.

**Comment by mnwhite** [comment]
To my recollection, I hardcoded the Lorenz curve targets, at least for one
of [net worth] or [liquid assets] because the dataset I was given was not
sufficiently documented to figure out which column should be used for those
measures.

**Comment by sbenthall** [comment]
I think that means this issue shouldn't be here.
HARK is just fine on Lorenz curves.
But the DemARK needs to be adjusted to use the HARK Lorenz curves and SCF dataset.
