### ISSUE TITLE
public_call decorator for checkConditions

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#670]
When checkConditions is called explicitly by a user from a console or notebook, it's assumed that they want to see verbose output even if they are not operating HARK verbosely.

This can be implemented with a decorator which does the context detection which swaps the logger configuration in and out.

This can be built on more robust logging
https://github.com/econ-ark/HARK/issues/283

**Comment by MridulS** [comment]
@sbenthall can you give a code example where this is happening? User can already control the verbose output.

**Comment by sbenthall** [comment]
The issue is checkConditions:
https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsIndShockModel.py#L1656

Should it be verbose or not, by default?

It has been argued that if it is called automatically in solution code, it should not be verbose.
But that if it is called manually by the user in, say, a Jupyter notebook, then it should be verbose.

It would be nice if this logic, which is rather complex, were not threaded through the model code.

So my proposal in this issue is that we have a decorator for this method (and maybe others) that detects the context in which the method is called and adjusts the verbosity setting accordinging.

This is connected to #130, which in my view is higher priority.

**Comment by MridulS** [comment]
That sounds nice indeed! Have you seen this kind of logging implemented in any other library yet? Would like to see how others deal with this.

**Comment by llorracc** [comment]
@sbenthall , @MridulS 

This is a to-do item still, right, not something that has actually been done?  

Mridul, do you know how to do it?  Would it be quick to do?

**Comment by sbenthall** [comment]
@MridulS I have not seen this sort of thing implemented anywhere else. It is the best idea I can come up with based on requirements from @llorracc articulated in GitHub issues and project discussion. I don't think these requirements are common.

**Comment by llorracc** [comment]
For present purposes, it will be easy enough to handle this with explicit verbosity directives in the notebook I've made.  My proposal perhaps reflects overengineering.  If it were commonly done, and obvious how to do it, then it would be worth doing.  Since neither of those seems to be true, I'd like to signal that this is, at best, low priority.

**Comment by sbenthall** [comment]
Ah, ok. So to confirm: the current expected usage pattern on this is to default to non-verbose, but to allow the user to explicitly raise verbosity when calling a command from a notebook?

**Comment by llorracc** [comment]
Yes, that's the idea.  If they are sitting there typing the command into a notebook, they are likely a bit of a newbie to the model and trying to understand it, and are in a context where they are very likely to be interested in the results at least with respect to the most extreme conditions, like "sorry stupid user you've given me parameter values for which the solution is degenerate" (using of course the more polite language we have already incorporated in checkConditions).  If embedded in a noninteractive program, we can trust that the user will choose the level of verbosity.

**Comment by sbenthall** [comment]
OK, I believe we can close this ticket then.
Verbosity is a documented feature of this method:
https://hark.readthedocs.io/en/latest/reference/ConsumptionSaving/ConsIndShockModel.html?highlight=checkConditions#HARK.ConsumptionSaving.ConsIndShockModel.PerfForesightConsumerType.checkCondition
