### ISSUE TITLE
remove update() method from TractableBufferStockModel ?

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#675]
https://github.com/econ-ark/HARK/blob/89cd5c0d3099063ce725b2bdb0eb93df24414a88/HARK/ConsumptionSaving/TractableBufferStockModel.py#L356

It's in the codebase to provide compatibility with cstwMPC agents.

**Comment by mnwhite** [comment]
I can't remember if cstwMPC even offers this as an option anymore.  It's
definitely not in the paper, but it was a feature we added early on to show
how AgentType subclasses could be swapped in and out.
