### ISSUE TITLE
Code inspection and analysis, deepsource 

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#676]
There are a bunch of tools available for code analysis of python codebases, and I just ran though HARK through it and it has caught a bunch of issues, an example setup -> https://deepsource.io/gh/MridulS/HARK/

Should we setup something like this to run on the master branch?

**Comment by mnwhite** [comment]
@MridulS Is this essentially covered by our linter and formatter pre-commit routine?

**Comment by MridulS** [comment]
Yeah, it should. We can always add more ruff things.
