### ISSUE TITLE
lifecycle.py - why does it exist?

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#685]
@sbenthall

**Comment by sbenthall** [comment]
Yikes. Looks like in that commit I included a lot of stuff I shouldn't have from my working directory.
https://github.com/econ-ark/HARK/commit/d43c35eb89e3792b1222f53902ffcd6e29bd9a49

Sloppy work; my apologies. 
It should be removed; I'll submit a PR for it.
