### ISSUE TITLE
Docs typos - aleph, CRRA and Livfa

### ISSUE THREAD

**Issue by dentarthur** [econ-ark/HARK#707]
Gentle Introduction at:
https://hark.readthedocs.io/en/latest/example_notebooks/Gentle-Intro-To-HARK.html

1) Hebrew letter "Aleph" appears. Normally only used for infinite cardinals.
I would guess that the intention was to use latex \alpha not \aleph in:

https://raw.githubusercontent.com/econ-ark/HARK/master/examples/Gentle-Intro/Gentle-Intro-To-HARK.ipynb

There are also two other likely latex errors highlighted in red at the above html page.

2) \CRRA

3) \Livfa

Only just started reading this so I won't attempt to fix using the "Edit on Github" link:

 https://github.com/econ-ark/HARK/blob/master/Documentation/example_notebooks/Gentle-Intro-To-HARK.ipynb
 
 Better for somebody familiar with intended result for all three errors to do it.
 
 PS Thanks for this software!!! I hope to get involved as soon as I can.

**Comment by mnwhite** [comment]
$\aleph$ was intentional in this case, being taken from the notation in a
particular set of lecture notes.  In most other places, we use
$\cancel{\mathsf{D}}$ for survival probability `LivPrb`.

**Comment by mnwhite** [comment]
This notebook has been extensively revised since this issue was filed. Closing.
