### ISSUE TITLE
LaborIntMargModel's example is broken

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#721]
When ConsumerParameters.py was deleted, the example dictionaries for the intensive margin labor model were not moved into ConsLaborModel.py.  This wasn't noticed because there's no automated test for the file.

Need to go look at an old commit and copy-paste those dictionaries into the model file, and remove the reference to ConsumerParameters in the imports.

**Comment by MridulS** [comment]
fixed in https://github.com/econ-ark/HARK/pull/729
