### ISSUE TITLE
Sync up Python and Numpy deprecation according to NEP 29 for HARK releases

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#738]
https://numpy.org/neps/nep-0029-deprecation_policy.html

There is a standard [support table](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) which is supposed to standardise the deprecation of python and numpy versions across scientific python packages.

I suggest we start following this and start updating min required version of python of numpy according to this.

**Comment by llorracc** [comment]
Sounds good to me.  I am hereby making you responsible for implementing.

**Comment by MridulS** [comment]
for reference: next release of HARK(0.10.7) should be tested for python3.7+ and numpy1.16+

**Comment by sbenthall** [comment]
This is a great idea.
Strong +1 for any proposal that aligns Econ-ARK with SciPy standards.

**Comment by MridulS** [comment]
Now a part of the release checklist https://github.com/econ-ark/OverARK/wiki/Release-Checklist
