### ISSUE TITLE
PerfForesightConsumerType problem

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#742]
Hi,

When Matt Zahn and I were trying to figure out why we were not able to replicate CGM(2005), one of the things we did was to take  the PortfolioConsumerType, turn off all the shocks and see if the solution matched the perfect foresight analytical solution (computed by ourselves). It did. We also compared results with the PerfForesightConsumerType.

Revisiting that test today, I am noticing some strange behavior from the PerfForesightConsumerType. Its solution does not match my self-computed analytical solution or that of the PortfolioConsumerType with all shocks turned off.

Here is an example: consider an agent that lives for 2 periods and has Rfree = DiscFac = PermGroFac = 1, no uncertainty and an artificial borrowing constraint at 0. His consumption function on the first period should be c(m) = min{m, (m+1)/2}. The kink of the consumption function should be at m=1. This is exactly what I get with the analytical solution and the PortfolioConsumerType, but the PerfForesightConsumerType's solution is shifted:

![image](https://user-images.githubusercontent.com/27739595/86305906-c9be9400-bbe0-11ea-881c-156775466eea.png)

Is there maybe an inconsistency with how market resources are interpreted across models?

**Comment by mnwhite** [comment]
Ugh, this looks like it code error, and a really significant one. I mean,
easy to fix, but embarrassing and bad.

I'm jumping in the shower now, will look at code when I get out. Your
analytic solution is correct.

**Comment by mnwhite** [comment]
Good catch.  There was a missing set of parentheses on line 514 of ConsIndShockModel.py, which is in the block of code that handles the special case of the borrowing constraint binding at all of the m_t values where kinks would appear.  This block gets triggered in T-1 almost surely, and thus the solution in periods near the terminal age was wrong. Well, technically the solution to any period that's a finite number of periods away from T-1 was wrong.

Interestingly, this error has no effect on the infinite horizon constrained solution, as the error gets washed away in the convergence process, as the errant line is unlikely to be reached beyond T-2 or so.

Anyway, I fixed it in #743 ... Thanks again!

**Comment by llorracc** [comment]
#743 has now been merged into core HARK. 

@Mv77, could you fetch/pull the update and see if the problem is fixed?

**Comment by mnwhite** [comment]
In case you're not already, you'll need to run HARK in developer mode, so that your Python knows to import from the repository directory rather than your packages library.

**Comment by Mv77** [comment]
> 
> 
> #743 has now been merged into core HARK.
> 
> @Mv77, could you fetch/pull the update and see if the problem is fixed?
> 
> If the problem is fixed, see if you can "close" this issue. (I'm not sure how permissions work -- maybe because you initiated the issue, you can close it?)

I have just tested it and it looks like the fix worked. I am now closing the issue.



> 
> 
> In case you're not already, you'll need to run HARK in developer mode, so that your Python knows to import from the repository directory rather than your packages library.

Thanks for the tip! I was not aware of the developer installation mode. Saves me a lot of re-installing :sweat:
