### ISSUE TITLE
Move TM's DemARK notebooks to examples/

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#746]
Move all these to the examples/ directory:

https://github.com/econ-ark/DemARK/pull/14
https://github.com/econ-ark/DemARK/pull/16
https://github.com/econ-ark/DemARK/pull/17
https://github.com/econ-ark/DemARK/pull/18

**Comment by MridulS** [comment]
https://github.com/econ-ark/DemARK/pull/14 -> https://github.com/econ-ark/HARK/blob/master/examples/ConsumptionSaving/example_ConsPrefShockModel.ipynb

https://github.com/econ-ark/DemARK/pull/16 -> https://github.com/econ-ark/HARK/blob/master/examples/ConsumptionSaving/example_ConsMarkovModel.ipynb

https://github.com/econ-ark/DemARK/pull/17 -> https://github.com/econ-ark/HARK/blob/master/examples/ConsumptionSaving/example_ConsMedModel.ipynb

https://github.com/econ-ark/DemARK/pull/18 -> https://github.com/econ-ark/HARK/blob/master/examples/ConsumptionSaving/example_ConsPrefShockModel.ipynb

GenIncProcessModel -> https://github.com/econ-ark/HARK/blob/master/examples/GenIncProcessModel/GenIncProcessModel.ipynb

All of these notebooks already exist in examples/ what we need to do is the move the documentation part in Markdown from the PRs to these example notebooks.
