### ISSUE TITLE
distribution truncation

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#804]
Was here: https://github.com/econ-ark/HARK/issues/519#issuecomment-632912381

From @llorracc 

> Reopening just because this seems like the natural place to elaborate a future improvement that should be on the agenda:
> 
> 1. For distributions that are unbounded, we should require an explicit truncation parameter
>    - For normal and lognormal distributions this should be a multiple of the number of standard deviations
>    - If the user does not specify a truncation point, we should use one by default (say, 5 standard deviations)
> 2. There are a number of ways to truncate. If you're discretizing anyway, a natural choice is simply to calculate the mean of the variable in the truncated region, and use that as a mass point. Having thought about it carefully, I've decided this is not optimal, because it means that the location of the lowest and highest mass points is not transparent to the human constructing the code, and requires a bit of extra accounting to keep track of.
> 3. Our default choice (I think; possibly further discussion will change my mind) should be to add the mass of the excluded points at exactly the truncation boundary. That is, if the choice is to truncate a normal distribution at 4 standard deviations, then there should be two symmetric mass points, at plus and minus 4 standard deviations from the mean, and with mass equal respectively to the mean value of the unbounded stochastic variable if its realization is lower than 4 standard deviations below the mean, or its mean value when its value is greater than 4 standard deviations above the mean.
>
> A mildly undesirable consequence of this choice:
> 
> 1. The standard deviation (and possibly the mean, for asymmetrical distributions like lognormal) of the truncated distribution will be slightly different from the standard deviation of the unbounded (untruncated) distribution.
> But on the positive side:
> 
> 1. It is transparent (as above)
> 2. No extra variables (like, the mean values mentioned above) need to be calculated
> (Crucially): Changes in the number of points used in the discretization will have no effect on the location of the minimum point (which is something to which numerical solutions can be exquisitely sensitive
> 3. The obvious "true" (Platonic) version of the model is the version as the number of discretization points goes to infinity. (This is useful in adjudicating which of competing numerical solutions is "closer" to "truth" which can be non-obvious for some discretization schemes).

**Comment by mnwhite** [comment]
This remains important. Our equiprobable discrete lognormal approximation method incorporates truncation, but there's no current way to indicate that *the distribution itself* is truncated, not just its approximation. This is part of the HARK 1 roadmap, so archiving with that tag.
