### ISSUE TITLE
track_vars cannot track PrefShkNow

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#808]
**Describe the bug**
Adding `PrefShkNow` to `track_vars` results in broken history records.

**To Reproduce**

Run this code:
https://gist.github.com/sbenthall/e398fd3c389a9cc094974c397e49b160

See this output:

```
python pref_test.py 
0.6904681186891202 0.69046812
/home/sb/projects/econ-ark/HARK/HARK/interpolation.py:1721: RuntimeWarning: All-NaN slice encountered
  y = self.compare(fx,axis=1)
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
```

**Expected behavior**

When `PrefShkNow` is removed from `track_vars`, and the corresponding print statement is removed, the numerical values of `cNrmNow` are displayed.

```
$ python pref_test.py 
0.6904681186891202 0.69046812
[[1.31820519 1.13599726 1.19117047 ... 1.15580804 0.92238984 0.79139412]
 [1.75227515 0.87249487 1.03166147 ... 1.09467154 1.04217198 0.81947656]
 [1.6132044  1.21100077 1.10807752 ... 1.04517571 0.97166597 0.93927158]
 ...
 [1.41013941 0.98367178 0.99266247 ... 1.19269696 1.00552796 1.02108079]
 [1.19004436 1.32309231 1.52353897 ... 1.10650642 0.87607768 0.92796219]
 [1.07060879 0.94171512 1.06713576 ... 0.94867343 0.8665761  0.93075895]]
```

I expect a similar thing when adding `PrefShkNow` to be tracked.

**Comment by mnwhite** [comment]
Try removing the call to makeShockHistory().

**Comment by sbenthall** [comment]
That worked....

Let's figure out how to make this documented/obvious and fail more gracefully.

**Comment by sbenthall** [comment]
Interesting.
WITH makeShockHistory, and WITHOUT the addition of PrefShkNow to track_vars, it also works.

So, this is specifically a problem with how adding it to track_vars interacts with makeShockHistory

**Comment by sbenthall** [comment]
Hmm. So, one thing I'm noticing is that a matrix full of `nan`s is what you initialize each shock variable with at the beginning of makeShockHistory

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L481

Another is that makeShockHistory calls initializeSim(), but in the test code is called _before_ initializeSim().

initializeSim() clears the history:
https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L423

which I think would erase everything already done by makeShockHistory.

But if I do NOT call initializeSim() after makeShockHistory(), I get this error:

```
Traceback (most recent call last):
  File "pref_test.py", line 20, in <module>
    agent.makeShockHistory()  # This is optional
  File "/home/sb/projects/econ-ark/HARK/HARK/core.py", line 687, in simulate
    self.simOnePeriod()
  File "/home/sb/projects/econ-ark/HARK/HARK/core.py", line 445, in simOnePeriod
    self.getMortality()  # Replace some agents with "newborns"
  File "/home/sb/projects/econ-ark/HARK/HARK/core.py", line 520, in getMortality
    who_dies = self.history['who_dies'][self.t_sim,:]
IndexError: index 10 is out of bounds for axis 0 with size 10
```
Which is dealing with the special case in getMortality which expects `self.read_shocks == True`

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L515-L516

**Comment by mnwhite** [comment]
initializeSim() needs to be called after makeShockHistory() because t_sim
has iterated up to T_sim, so it's trying to draw row 10 of
self.history['who_dies'], which only goes up to row 9.
