### ISSUE TITLE
We should add a routine to calculate the average value of any simulated object

### ISSUE THREAD

**Issue by llorracc-git** [econ-ark/HARK#81]
In DemosForFed, a method is defined for calculating the average value of consumption in the simulated economy.  There should be a general-purpose method which takes as its argument the object whose mean needs to be calculated, and returns that mean, so that in the future it will not be necessary to define specific methods for, say, wealth, and income, and so on.

**Comment by mnwhite** [comment]
Done in commit ad6f95.  getAvg is now a method of HARKobject, so this will be inherited by both AgentTypes and Markets (where it will be used).
