### ISSUE TITLE
Input checking for MarkovConsumerType

### ISSUE THREAD

**Issue by dclow** [econ-ark/HARK#83]
MarkovConsumerType could use more checking of its inputs.  It can give very weird error messages if it receives inputs that are just slightly different than what they should be.

For example, I wasted a lot of time with an infinite horizon version before I figured out that PermGroFac and LivPrb should be lists (of length 1, whose only element is a np.array), but Rfree should just be a numpy array.  Also, those arrays should be of shape (N,), where N is the number of Markov states.  Using an array of shape (N,1) also produced a very obscure error message

I imagine putting in checks at the beginning to verify that inputs are the right types and shapes could save a lot of people some of the hassle I went through

**Comment by mnwhite** [comment]
That's because LivPrb and PermGroFac are time-varying, so they need to be
lists at the top level (before being input to the solver for one period).

**Comment by dclow** [comment]
Just issued a PR to do this.  If the PR gets merged (maybe after dealing with issues you find), we can close this issue.

**Comment by mnwhite** [comment]
The PR that addressed this was merged back in October; closing.
