### ISSUE TITLE
figures and citations not rendering properly in RTD

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#839]
Figures don't seem to be rendering properly to the web accessible Read-The-Docs

For example:
https://hark.readthedocs.io/en/latest/examples/GenIncProcessModel/GenIncProcessModel.html 

Citations/links also don't seem to be render:
https://hark.readthedocs.io/en/latest/examples/LifecycleModel/LifecycleModel.html

I haven't touched RTD for a while. @MridulS any guesses as to what might be happening? I just  triggered a rebuild but it didn't fix it.

**Comment by MridulS** [comment]
Thanks for catching this, the documentation should be fixed now.

**Comment by MridulS** [comment]
https://hark.readthedocs.io/en/latest/examples/GenIncProcessModel/GenIncProcessModel.html should be https://hark.readthedocs.io/en/latest/example_notebooks/GenIncProcessModel.html
