### ISSUE TITLE
TractableConsumerType does not have all default parameters needed to solve()

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#845]
Related to #844 

Trying to write this automated simple automated test of basic `solve` and `simulate` functionality for TractableConsumerType:
https://gist.github.com/sbenthall/771121ec30afeaefdf24a9b7ac109997

This test fails on the `solve()` step with the following error:

```
        # Define some useful constants from model primitives
>       self.PermGroFacCmp = self.PermGroFac / (
            1.0 - self.UnempPrb
        )  # "uncertainty compensated" wage growth factor
E       AttributeError: 'TractableConsumerType' object has no attribute 'PermGroFac'

TractableBufferStockModel.py:362: AttributeError
```

The problem seems to be that there is no value of PermGroFac passed through to the constructor upon initialization by default.

**Comment by MridulS** [comment]
There is no startup dictionary for `TractableConsumerType` available.
