### ISSUE TITLE
How We Solve ... does not seem to be indexed in the documentation.

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#858]
A student was trying to figure out the details of how we solve the basic consumption problem.  I told him, "we have a whole notebook on that -- search the documentation for "How We Solve" or other similar terms.  Student came back and said nothing had appeared.

So, I went to hark.readthedocs.io, and was unable to find it myself, using the exact title "How we solve a model defined by the IndShockConsumerType class" or using any of various terms and phrases in the document.  After several minutes of searching, neither of us was able to find any trace of it.  

So I looked directly in the GitHub repo.  The file is there, under HARK/examples.  Is it being indexed in the docs and it's just that it's very hard to find the right search string to locate it?  If so, we should do something to make it much easier to find (like, link to it from other things that are easier to find).  

But I'm guessing that for some reason it's not being indexed at all.  (I couldn't figure out how to determine that explicitly).

**Comment by sbenthall** [comment]
RTD has been having build errors on the `latest` branch (master) for 1 week and 3 days at the time of this writing. I'll look into it.

**Comment by sbenthall** [comment]
PR #859 fixed the broken symlink to the How We Solve notebook, which explains why it was not rendered to RTD.

However, the build failure on RTD is preventing the update from going through.

This build failure is due to a breaking change in `nbconvert` that sphinx has not yet been updated to handle.

https://github.com/jupyter/nbconvert/issues/1126

**Comment by sbenthall** [comment]
These may be solved issues in Sphinx now; but we have Sphinx pinned to `Sphinx<=1.6.7`

This is due to issues raised in #406 -- compatibility with `numpydoc`.
