### ISSUE TITLE
Discrete interpolation

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#871]
This is a feature request, not a bug. It would be useful to provide interpolators for functions with continuous multidimensional domains and discrete ranges.

An example of this is is the share policy function `ShareFunc` of the `PortfolioConsumerType` when `DiscreteShareBool==True`. The policy function takes in (continuous) `mNrm` and outputs the optimal portfolio share, but the share is constrained to be in a discrete predefined set. Thus, a special interpolator with a restricted range must be used. This is done in the one-dimensional case starting at https://github.com/econ-ark/HARK/blob/b45cabdd5b3f4d079f1d11660e08167311dc9036/HARK/ConsumptionSaving/ConsPortfolioModel.py#L943

I anticipate multidimensional interpolators of this kind being useful in the future. The new portfolio model I'm working on could use one.

**Comment by llorracc** [comment]
Past experience with this sort of thing leads me to believe that the easy way to do this is also the best way:  You do a continuous linear interpolation, and then pick whichever of the discrete options is the closest.  I can elaborate if you would like, to help you implement it in your model.

**Comment by Mv77** [comment]
That makes a lot of sense. I will try it out!

**Comment by mnwhite** [comment]
Yeah, the method I used in PortfolioConsumerType doesn't extend nicely to
multidimensional interpolation.  I agree with Chris' suggestion, and the
easiest way to implement that is to have the discrete levels be
integer-valued in the interpolation, that way you can np.round the
continuous interpolated values, convert to int, and then just use that as
an indexing array for the true values:

`approx_levels = continuous_interpolator(x_vals, y_vals)`
`rounded_levels = np.round(approx_levels)`
`index_array = rounded_levels.astype(int)`
`output = value_lookup_array[index_array]`
`return output`

You could put all that on one line if you wanted, but it would be slightly
hard to read.

**Comment by Mv77** [comment]
Yes!

An n-dimensional nearest-neighbor routine seems like much more trouble than it'd be worth. Rounding in the range seems like a way better approach.

I'll close this and report back with how it goes in case you want to merge the tool into `interpolation.py`.

**Comment by Mv77** [comment]
![image](https://user-images.githubusercontent.com/27739595/99192681-1cd55580-2742-11eb-9ba5-7187a1cca046.png)

Worked like a charm! Thank you both.
