### ISSUE TITLE
Run a code coverage tool on our current testing regime

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#877]
something like https://codecov.io

**Comment by sbenthall** [comment]
https://gist.github.com/sbenthall/04ccebb4a32e3cc9c17226f9f6ce13a0

Modules that could use more test coverage:
- ConsIndShockModelFast.py 
- ConsMedModel.py
- ConsPortfolioModel.py 
- dcegm.py   
- estimation.py
- helpers.py
- interpolation.py
- numba.py
- utilities.py
