### ISSUE TITLE
Document time scaling of parameters

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#878]
From @llorracc 

> the point that the baseline version of HARK is calibrated so that a "period" is a year, and therefore the interest rate and rates of return and size of stochastic shocks are all at a yearly rate, is something that should be in the documentation somewhere

> "cstwMPC scale the yearly calibration to a quarterly calibration, and so if you want to think of the highest frequency with which any consumer rebalances their portfolio as being once a quarter, you could use their income calibration)."

I believe this raises questions more generally about how to document default parameters and their provenance.

Here is an example of where the default parameters in HARK are set. It is currently part of the default Model definition.

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsIndShockModel.py#L2008-L2035

Maybe there is a way to given these parameter objects docstrings.
It would be helpful if the _units_ of the parameters were documented ($$$, $$$/day, etc.).

I don't have a lot of insight into how these parameters were chosen; has @mnwhite recorded that anywhere?

**Comment by sbenthall** [comment]
On this topic, for this parameter:

`"aNrmInitMean": -6.0,  # Mean of log initial assets`

It would be best to specify the base of the log.

**Comment by mnwhite** [comment]
All models now have default parameter dictionaries, and they're all fully defined in the model file for each AgentType subclass. *Within* a file, dictionaries can be copied and adjusted (only a couple instances of this), but all the information is always there in the file.

As for how values were chosen: They're arbitrary or represent well known plausible values. E.g. no one is shocked by a risk free interest factor of 2% or 3%, and any CRRA between 1 and 5 is reasonable / defensible.

I believe all parameters in HARK are properly unitless.
