### ISSUE TITLE
Reconstitute FashionVictim example

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#968]
FashionVictim is a charming example of heterogeneous agent modeling with HARK.

Unfortunately, it has not been kept up to date with the libary. It hasn't even been rendered into a Jupyter notebook.

I've tried to repair it as part of the push to 1.0, but am running into bugs I can't fix.

What I think we should do is:
 - remove FashionVictim from HARK 1.0. (Removing it from 1.0 will NOT remove the code from version control; it will exist in all the previous releases)
 - have as a ticket the task of reconstituting it as an example based on the new HARK 1.0 foundation.

It would be a good introductory task for a student, for example.

**Comment by sbenthall** [comment]
Maybe take a look at this @nicksawhney

**Comment by mnwhite** [comment]
This model was long ago removed from HARK, closing.
