### ISSUE TITLE
Units of ShareFunc output

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#986]
I couldn't find the answer to this easily in the docs...

In the ConsPortfolioModel, the ShareFunc takes normalized market resources as input.
Is the _output_ of ShareFunc also normalized by permanent income?

**Comment by mnwhite** [comment]
No, it's unitless. It's the fraction of assets held in the risky asset.

**Comment by llorracc** [comment]
Although I believe @Mv77s more sophisticated portfolio model may work differently, you should check with him.

**Comment by Mv77** [comment]
- In ConsPortfolio: it's unitless as Matt said.
- In the new model I'm using: it does not exist. A similar object in that model is the share of income you put into the risky asset, and that's also unitless.

**Comment by mnwhite** [comment]
Closing for being essentially resolved / nothing to resolve.
