### ISSUE TITLE
New functionality: impulse response

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#99]
As a general purpose tool, HARK should have several varieties of impulse response.  I know that Edmund is already working on this, so this issue is kind of a freebie.

Comment here if you have particular features / flavors that you would like accommodated.  Or if you are Edmund and want to tell everyone what you're planning.

**Comment by shaunagm** [comment]
This is connected with Dolo/Dolark, need to think through how to incorporate into HARK.

**Comment by llorracc** [comment]
dolo has some good tools for doing impulse responses (I think called irf).  I very much like the implementation of simulation and irf's in dolo and think we should basically adopt dolo's tools.

**Comment by MridulS** [comment]
Best way to handle this is to get to the point where we can simulate HARK models in Dolo.
